/* ============================================================
   PyQuest — contenu de base : 3 actes, 18 chapitres.
   Chaque chapitre : 3 dalles-défis (challenges) + 1 grand projet.
   Ne pas modifier ce fichier pour ajouter du contenu :
   les nouveaux actes vont dans content/extensions.js
   ============================================================ */
(function(){
'use strict';
/* ================================================================
   CONTENU PÉDAGOGIQUE — 8 chapitres, 24 défis
   ================================================================ */
const CHAPTERS=[
{jour:'Jour 1',emoji:'👾',name:'La Grotte de l’Écho',mini:'print() et les textes',
 desc:'Un slime répète tout ce qu’on dit. Apprends à faire parler Python.',
 challenges:[
  {title:'Le premier sort',
   lesson:'<p>En Python, <code>print()</code> affiche du texte à l’écran. Le texte s’écrit entre guillemets — c’est une <b>chaîne de caractères</b> (string).</p><pre>print("Salut !")</pre><p>Attention : les guillemets et les parenthèses sont obligatoires, et Python respecte exactement ce que tu écris (majuscules, espaces, ponctuation).</p>',
   task:'<b>Mission :</b> affiche exactement <code>Bonjour, monde !</code>',
   starter:'# Écris ton premier sort ici :\n',
   hints:['Utilise print() avec le texte entre guillemets.','La virgule, l’espace et le « ! » comptent : print("Bonjour, monde !")'],
   solution:'print("Bonjour, monde !")',
   tests:[{out:['Bonjour, monde !']}]},
  {title:'Coller des textes',
   lesson:'<p>Le signe <code>+</code> colle deux chaînes ensemble (concaténation) :</p><pre>print("bon" + "jour")   # bonjour</pre><p>Et chaque <code>print()</code> écrit sur une <b>nouvelle ligne</b>.</p>',
   task:'<b>Mission :</b> ligne 1 — affiche <code>Python</code> en collant <code>"Py"</code> et <code>"thon"</code> avec +. Ligne 2 — affiche <code>est magique</code>.',
   starter:'',
   hints:['print("Py" + "thon") puis un deuxième print pour la suite.','Deux print() séparés = deux lignes.'],
   solution:'print("Py" + "thon")\nprint("est magique")',
   tests:[{out:['Python','est magique']}]},
  {title:'Le rire du slime',
   lesson:'<p>On peut <b>multiplier</b> une chaîne par un nombre pour la répéter :</p><pre>print("ab" * 3)   # ababab</pre>',
   task:'<b>Mission :</b> le slime doit rire ! Affiche <code>hahahahaha</code> en répétant <code>"ha"</code> 5 fois avec <code>*</code> (interdit de l’écrire à la main 😉).',
   starter:'',
   hints:['"ha" * 5 fabrique la chaîne répétée.','print("ha" * 5)'],
   solution:'print("ha" * 5)',
   tests:[{out:['hahahahaha']}]}]},

{jour:'Jour 1',emoji:'🗿',name:'Le Golem des Nombres',mini:'variables & calculs',
 desc:'Un golem de pierre ne comprend que les nombres. Stocke-les dans des variables.',
 challenges:[
  {title:'Ta première variable',
   lesson:'<p>Une <b>variable</b> est une boîte avec un nom, qui garde une valeur :</p><pre>vie = 100\nprint(vie)   # 100</pre><p>Le <code>=</code> veut dire « range cette valeur dans cette boîte ». Pas de guillemets autour des nombres !</p>',
   task:'<b>Mission :</b> crée une variable <code>force</code> qui vaut <code>42</code>, puis affiche-la.',
   starter:'',
   hints:['force = 42 (sans guillemets), puis print(force).','Dans print(force), pas de guillemets : on veut la valeur, pas le mot.'],
   solution:'force = 42\nprint(force)',
   tests:[{out:['42'],vars:{force:42}}]},
  {title:'La recette de la potion',
   lesson:'<p>Python calcule comme une super-calculatrice : <code>+ - * /</code>, et aussi <code>**</code> (puissance) et <code>%</code> (reste de division).</p><pre>total = 3 * 4 + 2   # 14</pre><p>La multiplication passe avant l’addition, comme en maths.</p>',
   task:'<b>Mission :</b> crée une variable <code>potion</code> qui vaut le résultat de <code>7 * 8 - 6</code> (écris le calcul, pas le résultat !), puis affiche-la.',
   starter:'',
   hints:['potion = 7 * 8 - 6','Puis print(potion) — tu dois voir 50.'],
   solution:'potion = 7 * 8 - 6\nprint(potion)',
   tests:[{out:['50'],vars:{potion:50}}]},
  {title:'La f-string enchantée',
   lesson:'<p>Pour mélanger texte et variables, la <b>f-string</b> est l’outil magique : un <code>f</code> devant les guillemets, et des accolades autour des variables :</p><pre>nom = "Rex"\nprint(f"Salut {nom} !")   # Salut Rex !</pre><p>On peut même mettre un calcul dans les accolades : <code>{niveau + 1}</code>.</p>',
   task:'<b>Mission :</b> crée <code>heros = "Nova"</code> et <code>niveau = 3</code>, puis affiche exactement <code>Nova passe au niveau 4</code> avec une f-string (le 4 doit venir de <code>niveau + 1</code>).',
   starter:'heros = "Nova"\nniveau = 3\n',
   hints:['print(f"... {heros} ... {niveau + 1}")','print(f"{heros} passe au niveau {niveau + 1}")'],
   solution:'heros = "Nova"\nniveau = 3\nprint(f"{heros} passe au niveau {niveau + 1}")',
   tests:[{out:['Nova passe au niveau 4']}]}]},

{jour:'Jour 2',emoji:'🦁',name:'Le Sphinx Binaire',mini:'conditions if / elif / else',
 desc:'Le sphinx pose des énigmes. Ton code doit décider tout seul de la réponse.',
 challenges:[
  {title:'Majeur ou mineur ?',
   lesson:'<p><code>if</code> exécute un bloc seulement si une condition est vraie ; <code>else</code> couvre le cas contraire :</p><pre>if age >= 18:\n    print("majeur")\nelse:\n    print("mineur")</pre><p>⚠️ Les deux-points <code>:</code> et l’<b>indentation</b> (4 espaces) sont obligatoires. Comparaisons : <code>== != &lt; &gt; &lt;= &gt;=</code>.</p>',
   task:'<b>Mission :</b> une variable <code>age</code> existe déjà (le sphinx la change à chaque essai !). Affiche <code>majeur</code> si <code>age &gt;= 18</code>, sinon <code>mineur</code>. Ne crée PAS la variable age toi-même.',
   starter:'# la variable age existe déjà, utilise-la directement\n',
   hints:['if age >= 18: puis un print indenté de 4 espaces.','N’oublie pas le bloc else: pour l’autre cas.'],
   solution:'if age >= 18:\n    print("majeur")\nelse:\n    print("mineur")',
   tests:[{pre:{age:20},out:['majeur']},{pre:{age:15},out:['mineur']},{pre:{age:18},out:['majeur']}]},
  {title:'Le bulletin magique',
   lesson:'<p>Pour tester plusieurs cas à la suite, on enchaîne avec <code>elif</code> (= « sinon si ») :</p><pre>if note >= 16:\n    print("top")\nelif note >= 12:\n    print("bien")\nelse:\n    print("à revoir")</pre><p>Python teste dans l’ordre et s’arrête au premier cas vrai.</p>',
   task:'<b>Mission :</b> la variable <code>note</code> existe déjà. Affiche <code>top</code> si note ≥ 16, <code>bien</code> si note ≥ 12, sinon <code>à revoir</code>.',
   starter:'# la variable note existe déjà\n',
   hints:['Trois blocs : if, elif, else — chacun avec son print indenté.','Commence par le cas le plus haut (>= 16), sinon « bien » attraperait tout.'],
   solution:'if note >= 16:\n    print("top")\nelif note >= 12:\n    print("bien")\nelse:\n    print("à revoir")',
   tests:[{pre:{note:17},out:['top']},{pre:{note:13},out:['bien']},{pre:{note:8},out:['à revoir']},{pre:{note:16},out:['top']},{pre:{note:12},out:['bien']}]},
  {title:'La porte à double verrou',
   lesson:'<p>On combine des conditions avec <code>and</code> (les deux doivent être vraies) et <code>or</code> (au moins une) :</p><pre>if cle and niveau >= 5:\n    ...</pre>',
   task:'<b>Mission :</b> les variables <code>cle</code> (True/False) et <code>niveau</code> existent déjà. Affiche <code>porte ouverte</code> si <code>cle</code> est vraie ET <code>niveau &gt;= 5</code>, sinon <code>accès refusé</code>.',
   starter:'# cle et niveau existent déjà\n',
   hints:['if cle and niveau >= 5:','Un seul if/else suffit avec and.'],
   solution:'if cle and niveau >= 5:\n    print("porte ouverte")\nelse:\n    print("accès refusé")',
   tests:[{pre:{cle:true,niveau:7},out:['porte ouverte']},{pre:{cle:true,niveau:3},out:['accès refusé']},{pre:{cle:false,niveau:9},out:['accès refusé']},{pre:{cle:true,niveau:5},out:['porte ouverte']}]}]},

{jour:'Jour 3',emoji:'🐲',name:'L’Hydre des Boucles',mini:'boucles for & while',
 desc:'Coupe une tête, deux repoussent. Seule la répétition automatique en vient à bout.',
 challenges:[
  {title:'Compter comme une machine',
   lesson:'<p>La boucle <code>for</code> répète un bloc pour chaque valeur. <code>range(1, 6)</code> produit 1, 2, 3, 4, 5 (le 6 est <b>exclu</b> !) :</p><pre>for i in range(1, 6):\n    print(i)</pre>',
   task:'<b>Mission :</b> affiche les nombres de 1 à 5, un par ligne, avec une boucle <code>for</code> et <code>range</code>.',
   starter:'',
   hints:['range(1, 6) — la fin est exclue, donc il faut aller jusqu’à 6.','for i in range(1, 6): puis print(i) indenté.'],
   solution:'for i in range(1, 6):\n    print(i)',
   tests:[{out:['1','2','3','4','5']}]},
  {title:'La somme du trésor',
   lesson:'<p>Un grand classique : l’<b>accumulateur</b>. On part de 0 et on ajoute à chaque tour :</p><pre>total = 0\nfor i in range(1, 4):\n    total = total + i\nprint(total)   # 6</pre><p>Raccourci : <code>total += i</code>.</p>',
   task:'<b>Mission :</b> calcule la somme de tous les nombres de 1 à 100 avec une boucle, puis affiche le total (indice : ça fait 5050).',
   starter:'total = 0\n',
   hints:['range(1, 101) pour aller jusqu’à 100 inclus.','Dans la boucle : total += i. Le print(total) est APRÈS la boucle (non indenté).'],
   solution:'total = 0\nfor i in range(1, 101):\n    total += i\nprint(total)',
   tests:[{out:['5050']}]},
  {title:'Compte à rebours',
   lesson:'<p>La boucle <code>while</code> répète TANT QUE la condition est vraie :</p><pre>n = 3\nwhile n > 0:\n    print(n)\n    n = n - 1</pre><p>⚠️ Si tu oublies de changer <code>n</code>, la boucle ne s’arrête jamais !</p>',
   task:'<b>Mission :</b> avec un <code>while</code>, affiche 5, 4, 3, 2, 1 (un par ligne) puis <code>Boum !</code> après la boucle.',
   starter:'n = 5\n',
   hints:['while n > 0: … et à l’intérieur n = n - 1 (ou n -= 1).','print("Boum !") se place après la boucle, sans indentation.'],
   solution:'n = 5\nwhile n > 0:\n    print(n)\n    n -= 1\nprint("Boum !")',
   tests:[{out:['5','4','3','2','1','Boum !']}]}]},

{jour:'Jour 4',emoji:'🐍',name:'Le Serpent des Listes',mini:'listes & index',
 desc:'Un serpent fait de cases numérotées. Chaque case cache un objet.',
 challenges:[
  {title:'Ton inventaire',
   lesson:'<p>Une <b>liste</b> range plusieurs valeurs dans l’ordre :</p><pre>sac = ["épée", "bouclier"]\nsac.append("potion")   # ajoute à la fin\nprint(len(sac))        # 3</pre>',
   task:'<b>Mission :</b> crée la liste <code>inventaire</code> avec <code>"épée"</code> et <code>"bouclier"</code>, ajoute <code>"potion"</code> avec <code>.append()</code>, puis affiche <code>len(inventaire)</code>.',
   starter:'',
   hints:['inventaire = ["épée", "bouclier"]','inventaire.append("potion") puis print(len(inventaire)) → 3'],
   solution:'inventaire = ["épée", "bouclier"]\ninventaire.append("potion")\nprint(len(inventaire))',
   tests:[{out:['3'],vars:{inventaire:['épée','bouclier','potion']}}]},
  {title:'Vider le sac',
   lesson:'<p>La boucle <code>for</code> parcourt directement une liste, élément par élément :</p><pre>for objet in sac:\n    print(objet)</pre>',
   task:'<b>Mission :</b> une liste <code>butin</code> existe déjà (contenu variable !). Affiche chaque objet du butin, un par ligne, avec une boucle.',
   starter:'# la liste butin existe déjà\n',
   hints:['for objet in butin:','print(objet) indenté dans la boucle — surtout ne liste rien à la main.'],
   solution:'for objet in butin:\n    print(objet)',
   tests:[{pre:{butin:['or','rubis','carte']},out:['or','rubis','carte']},{pre:{butin:['plume']},out:['plume']}]},
  {title:'Premier et dernier',
   lesson:'<p>Chaque case a un numéro (<b>index</b>) qui commence à <b>0</b>. Les index négatifs partent de la fin :</p><pre>sac[0]    # premier\nsac[-1]   # dernier\nsac[1:3]  # tranche : cases 1 et 2</pre>',
   task:'<b>Mission :</b> la liste <code>butin</code> existe déjà. Affiche son <b>premier</b> élément, puis son <b>dernier</b> (utilise <code>[0]</code> et <code>[-1]</code>).',
   starter:'# la liste butin existe déjà\n',
   hints:['print(butin[0]) pour le premier.','print(butin[-1]) pour le dernier, quelle que soit la taille.'],
   solution:'print(butin[0])\nprint(butin[-1])',
   tests:[{pre:{butin:['arc','flèche','carquois']},out:['arc','carquois']},{pre:{butin:['perle','coquillage']},out:['perle','coquillage']}]}]},

{jour:'Jour 5',emoji:'👺',name:'Le Gardien des Clés',mini:'dictionnaires',
 desc:'Il ne répond qu’aux bonnes clés. Chaque clé ouvre une valeur.',
 challenges:[
  {title:'La fiche du héros',
   lesson:'<p>Un <b>dictionnaire</b> associe des <b>clés</b> à des <b>valeurs</b> :</p><pre>hero = {"nom": "Kai", "pv": 100}\nprint(hero["nom"])   # Kai</pre><p>On lit une valeur avec <code>dico[clé]</code>.</p>',
   task:'<b>Mission :</b> crée le dictionnaire <code>hero</code> avec la clé <code>"nom"</code> valant <code>"Kai"</code> et la clé <code>"pv"</code> valant <code>100</code>. Puis affiche <code>hero["nom"]</code>.',
   starter:'',
   hints:['hero = {"nom": "Kai", "pv": 100}','print(hero["nom"]) — la clé entre guillemets !'],
   solution:'hero = {"nom": "Kai", "pv": 100}\nprint(hero["nom"])',
   tests:[{out:['Kai']}]},
  {title:'Le coup du gardien',
   lesson:'<p>On modifie une valeur comme on la lit :</p><pre>hero["pv"] = hero["pv"] - 30</pre><p>Si la clé n’existe pas encore, ça la crée !</p>',
   task:'<b>Mission :</b> le dictionnaire <code>hero</code> existe déjà (avec une clé <code>"pv"</code> qui varie). Le gardien frappe : retire <code>30</code> pv, puis affiche les pv restants.',
   starter:'# le dictionnaire hero existe déjà\n',
   hints:['hero["pv"] = hero["pv"] - 30 (ou hero["pv"] -= 30)','Puis print(hero["pv"]).'],
   solution:'hero["pv"] = hero["pv"] - 30\nprint(hero["pv"])',
   tests:[{pre:{hero:{__dict__:{nom:'Kai',pv:100}}},out:['70']},{pre:{hero:{__dict__:{nom:'Zia',pv:55}}},out:['25']}]},
  {title:'L’inventaire complet',
   lesson:'<p><code>.items()</code> permet de parcourir clés ET valeurs en même temps :</p><pre>for cle, valeur in sac.items():\n    print(cle, valeur)</pre>',
   task:'<b>Mission :</b> le dictionnaire <code>sac</code> existe déjà (objet → quantité). Pour chaque objet, affiche exactement <code>objet x quantité</code> (ex : <code>potion x 3</code>) avec une f-string.',
   starter:'# le dictionnaire sac existe déjà\n',
   hints:['for objet, quantite in sac.items():','print(f"{objet} x {quantite}") — attention aux espaces autour du x.'],
   solution:'for objet, quantite in sac.items():\n    print(f"{objet} x {quantite}")',
   tests:[{pre:{sac:{__dict__:{potion:3,corde:1}}},out:['potion x 3','corde x 1']},{pre:{sac:{__dict__:{gemme:7}}},out:['gemme x 7']}]}]},

{jour:'Jour 6',emoji:'🧙‍♂️',name:'L’Archimage des Fonctions',mini:'def & return',
 desc:'Il enferme ses sorts dans des parchemins réutilisables. Fais pareil.',
 challenges:[
  {title:'Ton premier parchemin',
   lesson:'<p>Une <b>fonction</b> est un bloc de code réutilisable. <code>def</code> la définit, <code>return</code> renvoie son résultat :</p><pre>def doubler(n):\n    return n * 2\n\nprint(doubler(5))   # 10</pre><p>⚠️ <code>return</code> renvoie une valeur, <code>print</code> ne fait que l’afficher — ce n’est pas pareil !</p>',
   task:'<b>Mission :</b> écris une fonction <code>saluer(nom)</code> qui <b>renvoie</b> (return !) la chaîne <code>Salut Ana !</code> quand on l’appelle avec <code>"Ana"</code> (avec une f-string). L’Archimage la testera avec plusieurs noms.',
   starter:'def saluer(nom):\n    ',
   hints:['return f"Salut {nom} !"','C’est bien return, pas print — la fonction doit RENVOYER le texte.'],
   solution:'def saluer(nom):\n    return f"Salut {nom} !"',
   tests:[{call:{fn:'saluer',args:['Ana'],want:'Salut Ana !'}},{call:{fn:'saluer',args:['Rex'],want:'Salut Rex !'}}]},
  {title:'Le calcul des dégâts',
   lesson:'<p>Une fonction peut prendre plusieurs paramètres et utiliser tout ce que tu connais (<code>max</code>, conditions…) :</p><pre>def plus_grand(a, b):\n    return max(a, b)</pre>',
   task:'<b>Mission :</b> écris <code>degats(force, defense)</code> qui renvoie <code>force - defense</code>, mais jamais moins que 0 (utilise <code>max(0, ...)</code> ou un if).',
   starter:'def degats(force, defense):\n    ',
   hints:['La différence peut être négative : il faut la bloquer à 0.','return max(0, force - defense)'],
   solution:'def degats(force, defense):\n    return max(0, force - defense)',
   tests:[{call:{fn:'degats',args:[10,3],want:7}},{call:{fn:'degats',args:[5,9],want:0}},{call:{fn:'degats',args:[8,8],want:0}}]},
  {title:'Pair ou impair',
   lesson:'<p>L’opérateur <code>%</code> donne le <b>reste</b> d’une division : <code>7 % 2</code> vaut 1, <code>8 % 2</code> vaut 0. Un nombre est pair si le reste par 2 vaut 0. Et une comparaison (<code>n % 2 == 0</code>) vaut déjà True ou False — on peut la <code>return</code> directement !</p>',
   task:'<b>Mission :</b> écris <code>est_pair(n)</code> qui renvoie <code>True</code> si n est pair, <code>False</code> sinon.',
   starter:'def est_pair(n):\n    ',
   hints:['n % 2 == 0 est vrai pour les nombres pairs.','return n % 2 == 0 — une seule ligne suffit, pas besoin de if !'],
   solution:'def est_pair(n):\n    return n % 2 == 0',
   tests:[{call:{fn:'est_pair',args:[4],want:true}},{call:{fn:'est_pair',args:[7],want:false}},{call:{fn:'est_pair',args:[0],want:true}}]}]},

{jour:'Jour 7',emoji:'🐉',name:'Le Dragon du Code',mini:'classes + BOSS FINAL',
 desc:'Le boss final. Il faudra TOUT utiliser : objets, méthodes, boucles, conditions.',
 challenges:[
  {title:'Forger un objet',
   lesson:'<p>Une <b>classe</b> est un moule à objets. <code>__init__</code> construit l’objet, <code>self</code> désigne l’objet lui-même :</p><pre>class Epee:\n    def __init__(self, nom):\n        self.nom = nom\n\ne = Epee("Excalibur")\nprint(e.nom)</pre>',
   task:'<b>Mission :</b> crée la classe <code>Potion</code> dont <code>__init__(self, nom, points)</code> enregistre <code>self.nom</code> et <code>self.points</code>. Puis crée <code>p = Potion("soin", 50)</code> et affiche <code>p.nom</code> puis <code>p.points</code>.',
   starter:'class Potion:\n    def __init__(self, nom, points):\n        ',
   hints:['Dans __init__ : self.nom = nom puis self.points = points','Ensuite p = Potion("soin", 50), print(p.nom), print(p.points)'],
   solution:'class Potion:\n    def __init__(self, nom, points):\n        self.nom = nom\n        self.points = points\n\np = Potion("soin", 50)\nprint(p.nom)\nprint(p.points)',
   tests:[{out:['soin','50']}]},
  {title:'Le rugissement',
   lesson:'<p>Les classes ont aussi des <b>méthodes</b> — des fonctions qui appartiennent à l’objet et lisent ses attributs via <code>self</code> :</p><pre>class Chat:\n    def __init__(self, n):\n        self.n = n\n    def parler(self):\n        return "miaou " * self.n</pre>',
   task:'<b>Mission :</b> crée la classe <code>Dragon</code> : <code>__init__(self, puissance)</code> stocke la puissance, et la méthode <code>rugir(self)</code> renvoie <code>"Graou" * self.puissance</code>. Puis crée <code>d = Dragon(3)</code> et affiche <code>d.rugir()</code>.',
   starter:'class Dragon:\n    def __init__(self, puissance):\n        self.puissance = puissance\n    ',
   hints:['def rugir(self): return "Graou" * self.puissance (indenté DANS la classe)','d = Dragon(3) puis print(d.rugir()) → GraouGraouGraou'],
   solution:'class Dragon:\n    def __init__(self, puissance):\n        self.puissance = puissance\n    def rugir(self):\n        return "Graou" * self.puissance\n\nd = Dragon(3)\nprint(d.rugir())',
   tests:[{out:['GraouGraouGraou']}]},
  {title:'⚔ LE SORT FINAL ⚔',
   lesson:'<p>Le Dragon ne craint qu’un sort légendaire (les pros l’appellent <b>FizzBuzz</b> — on le demande en vrai entretien d’embauche !). Il combine fonctions, conditions et modulo. Rappel : teste d’abord le cas « multiple de 3 ET de 5 », sinon il ne sera jamais atteint. Et pense à <code>str(n)</code> pour convertir un nombre en texte.</p>',
   task:'<b>Mission finale :</b> écris <code>sort_final(n)</code> qui renvoie <code>"FeuGlace"</code> si n est multiple de 3 ET de 5, <code>"Feu"</code> si multiple de 3 seulement, <code>"Glace"</code> si multiple de 5 seulement, et sinon le nombre <b>en texte</b> (<code>str(n)</code>).',
   starter:'def sort_final(n):\n    ',
   hints:['Commence par : if n % 3 == 0 and n % 5 == 0: return "FeuGlace"','Puis elif n % 3 == 0 → "Feu", elif n % 5 == 0 → "Glace", else → return str(n)'],
   solution:'def sort_final(n):\n    if n % 3 == 0 and n % 5 == 0:\n        return "FeuGlace"\n    elif n % 3 == 0:\n        return "Feu"\n    elif n % 5 == 0:\n        return "Glace"\n    else:\n        return str(n)',
   tests:[{call:{fn:'sort_final',args:[3],want:'Feu'}},{call:{fn:'sort_final',args:[5],want:'Glace'}},{call:{fn:'sort_final',args:[15],want:'FeuGlace'}},{call:{fn:'sort_final',args:[7],want:'7'}},{call:{fn:'sort_final',args:[9],want:'Feu'}},{call:{fn:'sort_final',args:[10],want:'Glace'}},{call:{fn:'sort_final',args:[30],want:'FeuGlace'}},{call:{fn:'sort_final',args:[1],want:'1'}}]}]}
];

/* ================================================================
   ACTES & EXTENSION — difficulté croissante
   ================================================================ */
const ACTES=[
 {name:'Acte I — Les Fondations',sub:'Semaine 1 · les bases du langage',dmg:12,xp:10,tick:8},
 {name:'Acte II — Les Terres Intermédiaires',sub:'Semaine 2 · ton RPG commence, la difficulté monte',dmg:16,xp:15,tick:8},
 {name:'Acte III — La Citadelle des Experts',sub:'Semaine 3 · niveau entretien d’embauche, tests cachés',dmg:22,xp:20,tick:10}];
CHAPTERS.forEach(c=>c.acte=0);

const A2=[
{jour:'Jour 8',emoji:'🧱',name:'Fil Rouge : Ton RPG — Fondations',mini:'PROJET · dicts + fonctions',
 desc:'Le projet fil rouge commence : tu vas construire TON propre jeu de rôle en Python, brique par brique.',
 challenges:[
  {title:'Le créateur de héros',
   lesson:'<p>🏗️ <b>Fil rouge :</b> à partir de maintenant, certains chapitres construisent un vrai programme — ton propre RPG. Première brique : une fonction-usine qui fabrique des personnages sous forme de dictionnaires.</p><pre>def creer(nom):\n    return {"nom": nom, "pv": 50}</pre><p>Chaque appel renvoie un personnage tout neuf.</p>',
   task:'<b>Mission :</b> écris <code>creer_personnage(nom)</code> qui renvoie le dictionnaire <code>{"nom": nom, "pv": 100, "force": 10}</code>.',
   starter:'def creer_personnage(nom):\n    ',
   hints:['return {"nom": nom, "pv": 100, "force": 10}','La clé "nom" reçoit le paramètre nom (sans guillemets autour du paramètre).'],
   solution:'def creer_personnage(nom):\n    return {"nom": nom, "pv": 100, "force": 10}',
   tests:[{call:{fn:'creer_personnage',args:['Ayla'],want:{__dict__:{nom:'Ayla',pv:100,force:10}}}},{call:{fn:'creer_personnage',args:['Bram'],want:{__dict__:{nom:'Bram',pv:100,force:10}}}}]},
  {title:'La fiche de personnage',
   lesson:'<p>Deuxième brique : afficher joliment un personnage. On lit un dictionnaire à l’intérieur d’une f-string :</p><pre>f"{perso[\'nom\']} a {perso[\'pv\']} PV"</pre><p>⚠️ Dans une f-string écrite avec des guillemets doubles, les clés s’écrivent avec des apostrophes simples.</p>',
   task:'<b>Mission :</b> écris <code>fiche(perso)</code> qui renvoie exactement <code>Ayla | PV 100 | Force 10</code> pour un perso nommé Ayla (format : <code>nom | PV x | Force y</code>).',
   starter:'def fiche(perso):\n    ',
   hints:["return f\"{perso['nom']} | PV {perso['pv']} | Force {perso['force']}\"",'Respecte les espaces autour des barres | .'],
   solution:'def fiche(perso):\n    return f"{perso[\'nom\']} | PV {perso[\'pv\']} | Force {perso[\'force\']}"',
   tests:[{call:{fn:'fiche',args:[{__dict__:{nom:'Ayla',pv:100,force:10}}],want:'Ayla | PV 100 | Force 10'}},{call:{fn:'fiche',args:[{__dict__:{nom:'Kor',pv:35,force:22}}],want:'Kor | PV 35 | Force 22'}}]},
  {title:'Le premier coup',
   lesson:'<p>Troisième brique : le combat ! Une fonction peut <b>modifier</b> un dictionnaire reçu en paramètre — la modification reste après l’appel. Et <code>max(0, x)</code> empêche les PV négatifs.</p>',
   task:'<b>Mission :</b> écris <code>coup(attaquant, defenseur)</code> : retire <code>attaquant["force"]</code> aux <code>defenseur["pv"]</code> (jamais en dessous de 0), puis renvoie les PV restants du défenseur.',
   starter:'def coup(attaquant, defenseur):\n    ',
   hints:['defenseur["pv"] = max(0, defenseur["pv"] - attaquant["force"])','Puis return defenseur["pv"]'],
   solution:'def coup(attaquant, defenseur):\n    defenseur["pv"] = max(0, defenseur["pv"] - attaquant["force"])\n    return defenseur["pv"]',
   tests:[{call:{fn:'coup',args:[{__dict__:{nom:'A',pv:100,force:10}},{__dict__:{nom:'B',pv:100,force:8}}],want:90}},{call:{fn:'coup',args:[{__dict__:{nom:'A',pv:10,force:50}},{__dict__:{nom:'B',pv:30,force:5}}],want:0}}]}]},

{jour:'Jour 9',emoji:'🕷️',name:'La Veuve des Erreurs',mini:'try / except / raise',
 desc:'Elle tisse des pièges dans ton code. Apprends à attraper les erreurs au vol.',
 challenges:[
  {title:'Le filet de sécurité',
   lesson:'<p>Quand une opération peut planter, on l’entoure d’un <code>try</code> ; le bloc <code>except</code> se déclenche seulement si l’erreur survient :</p><pre>try:\n    resultat = 10 / x\nexcept ZeroDivisionError:\n    print("impossible")</pre>',
   task:'<b>Mission :</b> les variables <code>a</code> et <code>b</code> existent déjà. Affiche le résultat de <code>a / b</code>… mais si b vaut 0, affiche <code>division impossible</code> au lieu de planter.',
   starter:'# a et b existent déjà\n',
   hints:['try: print(a / b) — puis un bloc except ZeroDivisionError:','Dans le except : print("division impossible")'],
   solution:'try:\n    print(a / b)\nexcept ZeroDivisionError:\n    print("division impossible")',
   tests:[{pre:{a:10,b:2},out:['5']},{pre:{a:7,b:0},out:['division impossible']},{pre:{a:9,b:3},out:['3']}]},
  {title:'Le traducteur méfiant',
   lesson:'<p><code>int("42")</code> convertit un texte en nombre — mais <code>int("abc")</code> lève une <code>ValueError</code>. Un bon programme s’y prépare au lieu de planter.</p>',
   task:'<b>Mission :</b> la variable <code>texte</code> existe déjà. Convertis-la en nombre avec <code>int()</code> et affiche son double. Si la conversion échoue (ValueError), affiche <code>nombre invalide</code>.',
   starter:'# texte existe déjà\n',
   hints:['try: n = int(texte) puis print(n * 2)','except ValueError: print("nombre invalide")'],
   solution:'try:\n    n = int(texte)\n    print(n * 2)\nexcept ValueError:\n    print("nombre invalide")',
   tests:[{pre:{texte:'21'},out:['42']},{pre:{texte:'abc'},out:['nombre invalide']},{pre:{texte:'100'},out:['200']}]},
  {title:'La banque du royaume',
   lesson:'<p>Ton code peut aussi <b>lever ses propres erreurs</b> avec <code>raise</code>, pour refuser une situation invalide :</p><pre>if montant &lt; 0:\n    raise ValueError("montant négatif")</pre><p>C’est comme ça qu’on écrit du code solide : on refuse tôt, clairement.</p>',
   task:'<b>Mission :</b> écris <code>retirer_or(bourse, montant)</code> : si <code>montant &gt; bourse</code>, lève <code>ValueError("pas assez d\'or")</code> avec raise ; sinon renvoie <code>bourse - montant</code>.',
   starter:'def retirer_or(bourse, montant):\n    ',
   hints:['if montant > bourse: raise ValueError("pas assez d\'or")','Sinon (après le if) : return bourse - montant'],
   solution:'def retirer_or(bourse, montant):\n    if montant > bourse:\n        raise ValueError("pas assez d\'or")\n    return bourse - montant',
   tests:[{call:{fn:'retirer_or',args:[100,30],want:70}},{call:{fn:'retirer_or',args:[50,50],want:0}},{callRaises:{fn:'retirer_or',args:[10,50],match:'ValueError'}}]}]},

{jour:'Jour 10',emoji:'🧵',name:'Le Tisseur de Chaînes',mini:'strings avancées + DEBUG',
 desc:'Maître des textes… et premier défi debug : répare du code cassé.',
 challenges:[
  {title:'Le cri de guerre',
   lesson:'<p>Les chaînes ont des méthodes puissantes qui s’enchaînent :</p><pre>"  chut  ".strip()        # "chut"\n"chut".upper()            # "CHUT"\n"  chut  ".strip().upper()  # les deux !</pre>',
   task:'<b>Mission :</b> écris <code>crier(phrase)</code> qui enlève les espaces autour (<code>strip</code>), met en MAJUSCULES (<code>upper</code>) et ajoute <code> !</code> à la fin.',
   starter:'def crier(phrase):\n    ',
   hints:['Enchaîne : phrase.strip().upper()','return phrase.strip().upper() + " !"'],
   solution:'def crier(phrase):\n    return phrase.strip().upper() + " !"',
   tests:[{call:{fn:'crier',args:['  victoire  '],want:'VICTOIRE !'}},{call:{fn:'crier',args:['en avant'],want:'EN AVANT !'}}]},
  {title:'Le parchemin corrompu',type:'debug',
   lesson:'<p>🐛 <b>Premier défi DEBUG !</b> Le code ci-contre existe déjà mais il est <b>cassé</b> — il compile, il tourne… et il donne un résultat faux. C’est le bug le plus dangereux. Lis-le ligne par ligne : que renvoie-t-il vraiment ?</p><p>Rappel : <code>phrase.split()</code> découpe une phrase en liste de mots.</p>',
   task:'<b>Mission debug :</b> <code>compter_mots("le chat dort")</code> devrait renvoyer 3, mais il renvoie 12. Trouve le bug et répare-le (une seule ligne à corriger).',
   starter:'def compter_mots(phrase):\n    mots = phrase.split()\n    return len(phrase)',
   hints:['Compare la ligne 2 et la ligne 3 : quelle variable contient les mots ?','len(phrase) compte les LETTRES. Il faut len(mots).'],
   solution:'def compter_mots(phrase):\n    mots = phrase.split()\n    return len(mots)',
   tests:[{call:{fn:'compter_mots',args:['le chat dort'],want:3}},{call:{fn:'compter_mots',args:['python'],want:1}},{call:{fn:'compter_mots',args:['un deux trois quatre'],want:4}}]},
  {title:'Le miroir maudit',
   lesson:'<p>Pour inverser un texte à la main, on construit le résultat lettre par lettre… en ajoutant chaque lettre <b>devant</b> :</p><pre>resultat = ""\npour chaque lettre :\n    resultat = lettre + resultat</pre><p>Après « a », « b », « c » → "a", puis "ba", puis "cba".</p>',
   task:'<b>Mission :</b> écris <code>inverser(mot)</code> qui renvoie le mot à l’envers, avec une boucle (pas de fonction toute faite).',
   starter:'def inverser(mot):\n    resultat = ""\n    ',
   hints:['for lettre in mot: puis resultat = lettre + resultat','N’oublie pas return resultat après la boucle (indentation !)'],
   solution:'def inverser(mot):\n    resultat = ""\n    for lettre in mot:\n        resultat = lettre + resultat\n    return resultat',
   tests:[{call:{fn:'inverser',args:['dragon'],want:'nogard'}},{call:{fn:'inverser',args:['abc'],want:'cba'}},{call:{fn:'inverser',args:['x'],want:'x'}}]}]},

{jour:'Jour 11',emoji:'⚗️',name:'L’Alchimiste des Listes',mini:'list comprehensions',
 desc:'Il transforme une liste entière en une seule formule. La syntaxe préférée des pros.',
 challenges:[
  {title:'La potion de duplication',
   lesson:'<p>La <b>compréhension de liste</b> crée une liste transformée en UNE ligne :</p><pre>doubles = [x * 2 for x in nombres]</pre><p>Ça se lit : « pour chaque x dans nombres, mets x*2 dans la nouvelle liste ». C’est LA syntaxe qu’on voit partout dans le vrai code Python.</p>',
   task:'<b>Mission :</b> la liste <code>nombres</code> existe déjà. Crée <code>doubles</code> avec une compréhension (chaque élément × 2) et affiche-la. <code>.append</code> est interdit !',
   starter:'# nombres existe déjà\n',
   forbid:['.append'],
   hints:['doubles = [x * 2 for x in nombres]','Puis print(doubles).'],
   solution:'doubles = [x * 2 for x in nombres]\nprint(doubles)',
   tests:[{pre:{nombres:[1,2,3]},out:['[2, 4, 6]']},{pre:{nombres:[5,10]},out:['[10, 20]']}]},
  {title:'Le filtre alchimique',
   lesson:'<p>On peut ajouter un <b>filtre</b> à la fin de la compréhension :</p><pre>petits = [x for x in nombres if x &lt; 10]</pre><p>Seuls les éléments qui passent le <code>if</code> entrent dans la liste.</p>',
   task:'<b>Mission :</b> la liste <code>nombres</code> existe déjà. Crée <code>pairs</code> contenant seulement les nombres pairs (compréhension + <code>if x % 2 == 0</code>), et affiche-la.',
   starter:'# nombres existe déjà\n',
   forbid:['.append'],
   hints:['pairs = [x for x in nombres if x % 2 == 0]','Même si aucun nombre ne passe, print(pairs) affichera [].'],
   solution:'pairs = [x for x in nombres if x % 2 == 0]\nprint(pairs)',
   tests:[{pre:{nombres:[1,2,3,4,5,6]},out:['[2, 4, 6]']},{pre:{nombres:[7,9]},out:['[]']}]},
  {title:'La vision de l’alchimiste',type:'predict',
   lesson:'<p>🔮 <b>Défi PRÉDICTION !</b> Cette fois tu n’écris pas de code : tu le <b>lis</b>. Exécute le programme ci-dessous dans ta tête et écris dans le grimoire EXACTEMENT ce qu’il affiche — une ligne de réponse par ligne affichée.</p><p>Rappel : une liste s’affiche avec crochets et apostrophes, ex : <code>[\'a\', \'b\']</code>, et les nombres sans guillemets : <code>[1, 9]</code>.</p>',
   task:'<b>Mission :</b> écris dans l’éditeur la sortie exacte du programme (3 lignes).',
   show:'mots = ["roc", "lave", "brume"]\ngrands = [m.upper() for m in mots if len(m) > 3]\nprint(grands)\nprint(len(mots))\nnombres = [1, 2, 3, 4]\nprint([n * n for n in nombres if n % 2 == 1])',
   starter:'',
   hints:['Quels mots ont plus de 3 lettres ? Ils passent en MAJUSCULES dans la liste.','len(mots) compte la liste D’ORIGINE. Et la dernière ligne : carrés des impairs seulement.'],
   solution:'',
   tests:[]}]},

{jour:'Jour 12',emoji:'🗡️',name:'Le Duelliste des Algorithmes',mini:'algos à la main · BOSS CHRONO ⏱️',timed:25,
 desc:'Il frappe toutes les 25 secondes tant que ton code est faux. Les fonctions toutes faites sont interdites.',
 challenges:[
  {title:'La recherche du traître',
   lesson:'<p>⚔️ Un <b>algorithme</b>, c’est une recette écrite à la main. La <b>recherche linéaire</b> : parcourir les positions une par une jusqu’à trouver.</p><pre>for i in range(len(liste)):\n    if liste[i] == cible:\n        # trouvé à la position i !</pre>',
   task:'<b>Mission :</b> écris <code>trouver(liste, cible)</code> qui renvoie la <b>position</b> de cible dans la liste, ou <code>-1</code> si absente. <code>.index()</code> interdit !',
   starter:'def trouver(liste, cible):\n    ',
   forbid:['.index'],
   hints:['Boucle sur les positions : for i in range(len(liste)):','Si liste[i] == cible : return i. Après la boucle : return -1.'],
   solution:'def trouver(liste, cible):\n    for i in range(len(liste)):\n        if liste[i] == cible:\n            return i\n    return -1',
   tests:[{call:{fn:'trouver',args:[['a','b','c'],'b'],want:1}},{call:{fn:'trouver',args:[['a'],'z'],want:-1}},{call:{fn:'trouver',args:[[4,7,9,7],7],want:1}}]},
  {title:'Le champion',
   lesson:'<p>Trouver le plus grand élément à la main : on garde un « champion » et on le compare à chaque concurrent :</p><pre>champion = liste[0]\npour chaque x :\n    si x &gt; champion : champion = x</pre>',
   task:'<b>Mission :</b> écris <code>plus_grand(liste)</code> sans utiliser <code>max()</code>, <code>sorted()</code> ni <code>.sort()</code>. La liste a toujours au moins un élément.',
   starter:'def plus_grand(liste):\n    ',
   forbid:['max(','sorted(','.sort('],
   hints:['Commence avec champion = liste[0], puis boucle sur la liste.','if x > champion: champion = x — et return champion à la fin.'],
   solution:'def plus_grand(liste):\n    champion = liste[0]\n    for x in liste:\n        if x > champion:\n            champion = x\n    return champion',
   tests:[{call:{fn:'plus_grand',args:[[3,9,2]],want:9}},{call:{fn:'plus_grand',args:[[-5,-2,-9]],want:-2}},{call:{fn:'plus_grand',args:[[7]],want:7}}]},
  {title:'Le compteur de voyelles',
   lesson:'<p>Un motif ultra-classique : le <b>compteur conditionnel</b>. On parcourt, on teste, on incrémente. Astuce : <code>lettre in "aeiou"</code> teste l’appartenance, et <code>.lower()</code> gère les majuscules.</p>',
   task:'<b>Mission :</b> écris <code>compter_voyelles(mot)</code> qui compte les voyelles (a, e, i, o, u), majuscules comprises.',
   starter:'def compter_voyelles(mot):\n    ',
   hints:['compteur = 0, puis for lettre in mot.lower():','if lettre in "aeiou": compteur += 1 — et return compteur.'],
   solution:'def compter_voyelles(mot):\n    compteur = 0\n    for lettre in mot.lower():\n        if lettre in "aeiou":\n            compteur += 1\n    return compteur',
   tests:[{call:{fn:'compter_voyelles',args:['Dragon'],want:2}},{call:{fn:'compter_voyelles',args:['PYTHON'],want:1}},{call:{fn:'compter_voyelles',args:['brrr'],want:0}}]}]}];
A2.forEach(c=>c.acte=1);

const A3=[
{jour:'Jour 13',emoji:'👑',name:'La Lignée des Dragons',mini:'héritage & POO avancée',
 desc:'Bienvenue dans la Citadelle. Ici, les classes engendrent des classes.',
 challenges:[
  {title:'Le moule à monstres',
   lesson:'<p>Révision musclée : une classe avec constructeur ET méthode qui lit <code>self</code> :</p><pre>class Loup:\n    def __init__(self, nom, pv):\n        self.nom = nom\n        self.pv = pv\n    def presenter(self):\n        return f"{self.nom} ({self.pv} PV)"</pre>',
   task:'<b>Mission :</b> crée la classe <code>Monstre</code> (constructeur <code>nom, pv</code> + méthode <code>presenter</code> qui renvoie <code>nom (pv PV)</code>). Puis crée <code>m = Monstre("Gobelin", 30)</code> et affiche <code>m.presenter()</code>.',
   starter:'class Monstre:\n    ',
   hints:['__init__(self, nom, pv) stocke self.nom et self.pv','def presenter(self): return f"{self.nom} ({self.pv} PV)"'],
   solution:'class Monstre:\n    def __init__(self, nom, pv):\n        self.nom = nom\n        self.pv = pv\n    def presenter(self):\n        return f"{self.nom} ({self.pv} PV)"\n\nm = Monstre("Gobelin", 30)\nprint(m.presenter())',
   tests:[{out:['Gobelin (30 PV)']}]},
  {title:'L’héritier',
   lesson:'<p>L’<b>héritage</b> : une classe fille récupère TOUT de sa classe mère, et ajoute ses propres pouvoirs :</p><pre>class Dragon(Monstre):\n    def cracher_feu(self):\n        return self.nom + " crache du feu !"</pre><p>Un Dragon a automatiquement <code>__init__</code> et <code>presenter</code> — pas besoin de les réécrire !</p>',
   task:'<b>Mission :</b> la classe Monstre est fournie. Crée <code>Dragon(Monstre)</code> avec la méthode <code>cracher_feu</code> qui renvoie <code>nom crache du feu !</code>. Puis <code>d = Dragon("Smaug", 200)</code>, affiche <code>d.presenter()</code> puis <code>d.cracher_feu()</code>.',
   starter:'class Monstre:\n    def __init__(self, nom, pv):\n        self.nom = nom\n        self.pv = pv\n    def presenter(self):\n        return f"{self.nom} ({self.pv} PV)"\n\nclass Dragon(Monstre):\n    ',
   hints:['Dans Dragon, une seule méthode suffit : cracher_feu(self).','return self.nom + " crache du feu !" — puis crée d et fais les 2 print.'],
   solution:'class Monstre:\n    def __init__(self, nom, pv):\n        self.nom = nom\n        self.pv = pv\n    def presenter(self):\n        return f"{self.nom} ({self.pv} PV)"\n\nclass Dragon(Monstre):\n    def cracher_feu(self):\n        return self.nom + " crache du feu !"\n\nd = Dragon("Smaug", 200)\nprint(d.presenter())\nprint(d.cracher_feu())',
   tests:[{out:['Smaug (200 PV)','Smaug crache du feu !']}]},
  {title:'Le boss réécrit',
   lesson:'<p>Une classe fille peut <b>redéfinir</b> une méthode héritée, tout en réutilisant celle du parent :</p><pre>class Boss(Monstre):\n    def __init__(self, nom, pv, rage):\n        Monstre.__init__(self, nom, pv)\n        self.rage = rage\n    def presenter(self):\n        return Monstre.presenter(self) + " !!!"</pre><p><code>Parent.methode(self, ...)</code> appelle la version du parent.</p>',
   task:'<b>Mission :</b> Monstre est fournie. Crée <code>Boss(Monstre)</code> : constructeur <code>(nom, pv, rage)</code> qui appelle <code>Monstre.__init__</code> puis stocke la rage, et <code>presenter</code> redéfinie qui renvoie la version du parent + <code> — rage 9</code> (via f-string sur self.rage). Puis <code>b = Boss("Ragnar", 500, 9)</code> et affiche <code>b.presenter()</code>.',
   starter:'class Monstre:\n    def __init__(self, nom, pv):\n        self.nom = nom\n        self.pv = pv\n    def presenter(self):\n        return f"{self.nom} ({self.pv} PV)"\n\nclass Boss(Monstre):\n    ',
   hints:['Dans __init__ du Boss : Monstre.__init__(self, nom, pv) puis self.rage = rage','def presenter(self): return Monstre.presenter(self) + f" — rage {self.rage}"'],
   solution:'class Monstre:\n    def __init__(self, nom, pv):\n        self.nom = nom\n        self.pv = pv\n    def presenter(self):\n        return f"{self.nom} ({self.pv} PV)"\n\nclass Boss(Monstre):\n    def __init__(self, nom, pv, rage):\n        Monstre.__init__(self, nom, pv)\n        self.rage = rage\n    def presenter(self):\n        return Monstre.presenter(self) + f" — rage {self.rage}"\n\nb = Boss("Ragnar", 500, 9)\nprint(b.presenter())',
   tests:[{out:['Ragnar (500 PV) — rage 9']}]}]},

{jour:'Jour 14',emoji:'🏛️',name:'L’Architecte des Données',mini:'piles, files + DEBUG',
 desc:'Les structures de données : la façon dont les vrais programmes rangent le monde.',
 challenges:[
  {title:'La pile d’assiettes',
   lesson:'<p>Une <b>pile</b> (stack) : le dernier arrivé est le premier sorti (LIFO). En Python, une simple liste suffit : <code>.append()</code> pour empiler, <code>.pop()</code> pour dépiler le DERNIER. C’est exactement le Ctrl+Z de tous les logiciels !</p>',
   task:'<b>Mission :</b> la liste <code>pile</code> existe déjà. Dépile le dernier élément avec <code>.pop()</code>, affiche-le, puis affiche la pile restante.',
   starter:'# pile existe déjà\n',
   hints:['dernier = pile.pop() — pop() SANS argument retire le dernier.','print(dernier) puis print(pile).'],
   solution:'dernier = pile.pop()\nprint(dernier)\nprint(pile)',
   tests:[{pre:{pile:['a','b','c']},out:['c',"['a', 'b']"]},{pre:{pile:[1,2]},out:['2','[1]']}]},
  {title:'La file d’attente',type:'predict',
   lesson:'<p>🔮 <b>Défi PRÉDICTION.</b> Une <b>file</b> (queue) : premier arrivé, premier servi (FIFO). <code>.pop(0)</code> retire le PREMIER élément, <code>.pop()</code> le dernier. Exécute ce programme dans ta tête et écris sa sortie exacte (4 lignes).</p>',
   task:'<b>Mission :</b> écris dans l’éditeur les 4 lignes exactes que ce programme affiche.',
   show:'file = ["Ana", "Bob", "Zoe"]\nfile.append("Max")\npremier = file.pop(0)\nprint(premier)\nprint(len(file))\nprint(file.pop())\nprint(file)',
   starter:'',
   hints:['Après append : ["Ana","Bob","Zoe","Max"]. pop(0) retire qui ?','La dernière ligne affiche une liste : format [\'Bob\', \'Zoe\'] avec apostrophes.'],
   solution:'',
   tests:[]},
  {title:'Le recenseur',type:'debug',
   lesson:'<p>🐛 <b>Défi DEBUG.</b> Compter les occurrences avec un dictionnaire est un motif fondamental :</p><pre>compteur[x] = compteur.get(x, 0) + 1</pre><p><code>.get(x, 0)</code> renvoie la valeur de x, ou 0 si la clé n’existe pas encore. Le code fourni a un bug subtil…</p>',
   task:'<b>Mission debug :</b> <code>compter(["pomme","or","pomme"])</code> devrait renvoyer <code>{\'pomme\': 2, \'or\': 1}</code>, mais toutes les valeurs restent à 1. Répare !',
   starter:'def compter(liste):\n    compteur = {}\n    for x in liste:\n        compteur[x] = 1\n    return compteur',
   hints:['compteur[x] = 1 ÉCRASE la valeur à chaque passage au lieu d’ajouter.','Remplace par : compteur[x] = compteur.get(x, 0) + 1'],
   solution:'def compter(liste):\n    compteur = {}\n    for x in liste:\n        compteur[x] = compteur.get(x, 0) + 1\n    return compteur',
   tests:[{call:{fn:'compter',args:[['pomme','or','pomme']],want:{__dict__:{pomme:2,or:1}}}},{call:{fn:'compter',args:[['x']],want:{__dict__:{x:1}}}},{hidden:true,call:{fn:'compter',args:[[]],want:{__dict__:{}}}}]}]},

{jour:'Jour 15',emoji:'🌀',name:'Le Miroir Récursif',mini:'récursivité + tri · BOSS CHRONO ⏱️',timed:20,
 desc:'Une fonction qui s’appelle elle-même… Il attaque toutes les 20 secondes.',
 challenges:[
  {title:'L’écho infini',
   lesson:'<p>La <b>récursivité</b> : une fonction qui s’appelle elle-même, avec 1) un <b>cas de base</b> qui arrête tout, 2) un appel sur un problème plus petit :</p><pre>def compte(n):\n    if n == 0:        # cas de base\n        return\n    compte(n - 1)     # plus petit</pre><p>La factorielle : <code>5! = 5 × 4 × 3 × 2 × 1 = 120</code>, et <code>n! = n × (n-1)!</code></p>',
   task:'<b>Mission :</b> écris <code>factorielle(n)</code> en récursif : si <code>n &lt;= 1</code> renvoie 1, sinon renvoie <code>n * factorielle(n - 1)</code>.',
   starter:'def factorielle(n):\n    ',
   hints:['Le cas de base d’abord : if n <= 1: return 1','Puis : return n * factorielle(n - 1)'],
   solution:'def factorielle(n):\n    if n <= 1:\n        return 1\n    return n * factorielle(n - 1)',
   tests:[{call:{fn:'factorielle',args:[5],want:120}},{call:{fn:'factorielle',args:[1],want:1}},{call:{fn:'factorielle',args:[0],want:1}},{hidden:true,call:{fn:'factorielle',args:[8],want:40320}}]},
  {title:'La suite du sage',
   lesson:'<p>La suite de Fibonacci : chaque nombre est la somme des deux précédents — 0, 1, 1, 2, 3, 5, 8, 13… Définition récursive parfaite : <code>fib(n) = fib(n-1) + fib(n-2)</code>, avec fib(0)=0 et fib(1)=1.</p>',
   task:'<b>Mission :</b> écris <code>fibonacci(n)</code> en récursif : si <code>n &lt;= 1</code> renvoie n, sinon la somme des deux appels précédents.',
   starter:'def fibonacci(n):\n    ',
   hints:['if n <= 1: return n  (ça couvre fib(0)=0 ET fib(1)=1)','return fibonacci(n - 1) + fibonacci(n - 2)'],
   solution:'def fibonacci(n):\n    if n <= 1:\n        return n\n    return fibonacci(n - 1) + fibonacci(n - 2)',
   tests:[{call:{fn:'fibonacci',args:[7],want:13}},{call:{fn:'fibonacci',args:[1],want:1}},{call:{fn:'fibonacci',args:[0],want:0}},{hidden:true,call:{fn:'fibonacci',args:[12],want:144}}]},
  {title:'Le grand tri',
   lesson:'<p>Le <b>tri à bulles</b>, premier vrai algorithme de tri : on compare chaque paire de voisins et on les échange s’ils sont dans le mauvais ordre — encore et encore :</p><pre>si liste[j] &gt; liste[j+1] :\n    échange-les (avec une variable temp)</pre><p>Échange : <code>temp = a</code> ; <code>a = b</code> ; <code>b = temp</code>.</p>',
   task:'<b>Mission :</b> écris <code>trier(liste)</code> (tri à bulles : double boucle) qui renvoie la liste triée en ordre croissant. <code>sorted()</code>, <code>.sort()</code>, <code>min()</code>, <code>max()</code> interdits !',
   starter:'def trier(liste):\n    n = len(liste)\n    ',
   forbid:['sorted(','.sort(','min(','max('],
   hints:['for i in range(n): puis for j in range(n - 1): à l’intérieur.','if liste[j] > liste[j + 1]: fais l’échange avec temp. Return liste à la fin.'],
   solution:'def trier(liste):\n    n = len(liste)\n    for i in range(n):\n        for j in range(n - 1):\n            if liste[j] > liste[j + 1]:\n                temp = liste[j]\n                liste[j] = liste[j + 1]\n                liste[j + 1] = temp\n    return liste',
   tests:[{call:{fn:'trier',args:[[3,1,2]],want:[1,2,3]}},{call:{fn:'trier',args:[[5]],want:[5]}},{hidden:true,call:{fn:'trier',args:[[9,-1,4,4,0]],want:[-1,0,4,4,9]}},{hidden:true,call:{fn:'trier',args:[[]],want:[]}}]}]},

{jour:'Jour 16',emoji:'🎭',name:'Le Juge des Entretiens',mini:'défis d’entretien · TESTS CACHÉS',
 desc:'De vraies questions d’entretien d’embauche. Ton code est jugé sur des cas que tu ne vois pas.',
 challenges:[
  {title:'Le mot miroir',
   lesson:'<p>🎭 <b>Tests cachés :</b> à partir d’ici, ton code est aussi testé sur des cas <b>invisibles</b> — comme sur LeetCode ou en entretien. Un palindrome se lit pareil dans les deux sens : radar, kayak. Stratégie : inverse le mot (tu sais le faire !) et compare.</p>',
   task:'<b>Mission :</b> écris <code>est_palindrome(mot)</code> qui renvoie True/False. Exemples visibles : radar → True, lune → False. <b>+ 5 tests cachés.</b>',
   starter:'def est_palindrome(mot):\n    ',
   hints:['Inverse le mot avec une boucle (resultat = lettre + resultat), puis compare.','return resultat == mot — pense au mot vide et au mot d’une lettre (cachés !).'],
   solution:'def est_palindrome(mot):\n    resultat = ""\n    for lettre in mot:\n        resultat = lettre + resultat\n    return resultat == mot',
   tests:[{call:{fn:'est_palindrome',args:['radar'],want:true}},{call:{fn:'est_palindrome',args:['lune'],want:false}},{hidden:true,call:{fn:'est_palindrome',args:['kayak'],want:true}},{hidden:true,call:{fn:'est_palindrome',args:[''],want:true}},{hidden:true,call:{fn:'est_palindrome',args:['a'],want:true}},{hidden:true,call:{fn:'est_palindrome',args:['abba'],want:true}},{hidden:true,call:{fn:'est_palindrome',args:['abab'],want:false}}]},
  {title:'Les lettres jumelles',
   lesson:'<p>Deux mots sont des <b>anagrammes</b> s’ils contiennent exactement les mêmes lettres : chien / niche. L’astuce d’entretien : trie les lettres des deux mots — si les résultats sont égaux, ce sont des anagrammes. <code>sorted("cab")</code> renvoie <code>[\'a\', \'b\', \'c\']</code>.</p>',
   task:'<b>Mission :</b> écris <code>sont_anagrammes(a, b)</code> qui renvoie True/False. <b>+ 3 tests cachés.</b>',
   starter:'def sont_anagrammes(a, b):\n    ',
   hints:['sorted(a) trie les lettres d’un mot en liste.','return sorted(a) == sorted(b) — une ligne !'],
   solution:'def sont_anagrammes(a, b):\n    return sorted(a) == sorted(b)',
   tests:[{call:{fn:'sont_anagrammes',args:['chien','niche'],want:true}},{call:{fn:'sont_anagrammes',args:['chat','rat'],want:false}},{hidden:true,call:{fn:'sont_anagrammes',args:['',''],want:true}},{hidden:true,call:{fn:'sont_anagrammes',args:['aab','aba'],want:true}},{hidden:true,call:{fn:'sont_anagrammes',args:['ab','abb'],want:false}}]},
  {title:'Le favori de la foule',
   lesson:'<p>Question d’entretien classique : trouver l’élément le plus fréquent. Plan en deux temps : 1) compter avec un dictionnaire (<code>compteur[x] = compteur.get(x, 0) + 1</code>), 2) parcourir le dictionnaire pour trouver la clé au plus grand compte.</p>',
   task:'<b>Mission :</b> écris <code>plus_frequent(liste)</code> qui renvoie l’élément le plus fréquent (il y a toujours un gagnant unique, liste jamais vide). <b>+ 3 tests cachés.</b>',
   starter:'def plus_frequent(liste):\n    compteur = {}\n    ',
   hints:['Étape 1 : remplis le compteur avec .get(x, 0) + 1.','Étape 2 : meilleur = liste[0], puis for x in compteur.keys(): compare compteur[x] > compteur[meilleur].'],
   solution:'def plus_frequent(liste):\n    compteur = {}\n    for x in liste:\n        compteur[x] = compteur.get(x, 0) + 1\n    meilleur = liste[0]\n    for x in compteur.keys():\n        if compteur[x] > compteur[meilleur]:\n            meilleur = x\n    return meilleur',
   tests:[{call:{fn:'plus_frequent',args:[[1,2,2,3]],want:2}},{hidden:true,call:{fn:'plus_frequent',args:[['a','b','a']],want:'a'}},{hidden:true,call:{fn:'plus_frequent',args:[[5]],want:5}},{hidden:true,call:{fn:'plus_frequent',args:[[1,1,2,2,2]],want:2}}]}]},

{jour:'Jour 17',emoji:'🏰',name:'Fil Rouge Final : Ton RPG Complet',mini:'BOSS FINAL · classes + tout · CHRONO ⏱️',timed:18,
 desc:'L’assemblage final : ton RPG complet en POO. Il attaque toutes les 18 secondes. Tout ce que tu as appris sert ici.',
 challenges:[
  {title:'La classe Héros',
   lesson:'<p>🏗️ <b>Fil rouge, assemblage final !</b> Ton RPG passe en POO. Le scénario de test en bas du grimoire est fourni — <b>ne le modifie pas</b>, complète seulement la méthode. Rappels : <code>min(100, x)</code> plafonne à 100, et une méthode peut renvoyer True ou False.</p>',
   task:'<b>Mission :</b> complète <code>boire_potion</code> : s’il reste des potions → retire 1 potion, rends 30 PV (plafond 100) et renvoie True ; sinon renvoie False. Sortie attendue du scénario : True, 70, True, 100, False.',
   starter:'class Heros:\n    def __init__(self, nom):\n        self.nom = nom\n        self.pv = 100\n        self.potions = 2\n\n    def boire_potion(self):\n        pass  # ← remplace par ton code\n\n# --- scénario de test (ne modifie pas) ---\nh = Heros("Rin")\nh.pv = 40\nprint(h.boire_potion())\nprint(h.pv)\nprint(h.boire_potion())\nprint(h.pv)\nprint(h.boire_potion())',
   hints:['if self.potions > 0: … else: return False','Dans le if : self.potions -= 1, puis self.pv = min(100, self.pv + 30), puis return True'],
   solution:'class Heros:\n    def __init__(self, nom):\n        self.nom = nom\n        self.pv = 100\n        self.potions = 2\n\n    def boire_potion(self):\n        if self.potions > 0:\n            self.potions -= 1\n            self.pv = min(100, self.pv + 30)\n            return True\n        return False\n\n# --- scénario de test (ne modifie pas) ---\nh = Heros("Rin")\nh.pv = 40\nprint(h.boire_potion())\nprint(h.pv)\nprint(h.boire_potion())\nprint(h.pv)\nprint(h.boire_potion())',
   tests:[{out:['True','70','True','100','False']}]},
  {title:'Le duel de méthodes',
   lesson:'<p>Deux objets qui interagissent : le héros attaque un monstre — la méthode reçoit l’AUTRE objet en paramètre et modifie ses attributs. C’est le cœur de tout moteur de jeu.</p>',
   task:'<b>Mission :</b> complète <code>attaquer(self, monstre)</code> : retire <code>self.force</code> aux PV du monstre (plancher 0, avec max) et renvoie <code>nom inflige X dégâts à cible</code> en f-string. Sortie attendue : le message, 20, le message, 0.',
   starter:'class Monstre:\n    def __init__(self, nom, pv):\n        self.nom = nom\n        self.pv = pv\n\nclass Heros:\n    def __init__(self, nom, force):\n        self.nom = nom\n        self.force = force\n\n    def attaquer(self, monstre):\n        pass  # ← ton code : inflige les dégâts, renvoie le message\n\n# --- scénario de test (ne modifie pas) ---\nh = Heros("Rin", 30)\nm = Monstre("Ogre", 50)\nprint(h.attaquer(m))\nprint(m.pv)\nprint(h.attaquer(m))\nprint(m.pv)',
   hints:['monstre.pv = max(0, monstre.pv - self.force)','return f"{self.nom} inflige {self.force} dégâts à {monstre.nom}"'],
   solution:'class Monstre:\n    def __init__(self, nom, pv):\n        self.nom = nom\n        self.pv = pv\n\nclass Heros:\n    def __init__(self, nom, force):\n        self.nom = nom\n        self.force = force\n\n    def attaquer(self, monstre):\n        monstre.pv = max(0, monstre.pv - self.force)\n        return f"{self.nom} inflige {self.force} dégâts à {monstre.nom}"\n\n# --- scénario de test (ne modifie pas) ---\nh = Heros("Rin", 30)\nm = Monstre("Ogre", 50)\nprint(h.attaquer(m))\nprint(m.pv)\nprint(h.attaquer(m))\nprint(m.pv)',
   tests:[{out:['Rin inflige 30 dégâts à Ogre','20','Rin inflige 30 dégâts à Ogre','0']}]},
  {title:'⚔ LE COMBAT FINAL ⚔',
   lesson:'<p>Le sort ultime : un <b>simulateur de combat complet</b>. Une boucle infinie (<code>while True:</code>), des tours alternés, des conditions de victoire. Le héros frappe TOUJOURS en premier. C’est un vrai moteur de jeu en 8 lignes — et il est jugé sur des <b>tests cachés</b>.</p>',
   task:'<b>Mission finale :</b> écris <code>simuler_combat(pv_heros, force_heros, pv_monstre, force_monstre)</code>. À chaque tour : le héros frappe (le monstre perd force_heros PV) — si le monstre tombe à 0 ou moins, renvoie <code>"héros"</code> ; sinon le monstre riposte — si le héros tombe à 0 ou moins, renvoie <code>"monstre"</code>. Les forces valent toujours au moins 1.',
   starter:'def simuler_combat(pv_heros, force_heros, pv_monstre, force_monstre):\n    while True:\n        ',
   hints:['Dans la boucle : pv_monstre -= force_heros, puis if pv_monstre <= 0: return "héros"','Ensuite pv_heros -= force_monstre, et if pv_heros <= 0: return "monstre"'],
   solution:'def simuler_combat(pv_heros, force_heros, pv_monstre, force_monstre):\n    while True:\n        pv_monstre -= force_heros\n        if pv_monstre <= 0:\n            return "héros"\n        pv_heros -= force_monstre\n        if pv_heros <= 0:\n            return "monstre"',
   tests:[{call:{fn:'simuler_combat',args:[100,20,50,10],want:'héros'}},{call:{fn:'simuler_combat',args:[30,5,100,50],want:'monstre'}},{hidden:true,call:{fn:'simuler_combat',args:[10,10,10,10],want:'héros'}},{hidden:true,call:{fn:'simuler_combat',args:[100,1,100,2],want:'monstre'}},{hidden:true,call:{fn:'simuler_combat',args:[1,1,1,100],want:'héros'}}]}]}];
A3.forEach(c=>c.acte=2);
CHAPTERS.push(...A2,...A3);

/* ================================================================
   GRANDS PROJETS — chaque monstre garde un projet qui assemble
   tout le chapitre (les dalles 💠 du chemin sont les petits défis)
   ================================================================ */
const PROJETS=[
{title:'PROJET · La bannière du village',
 lesson:'<p>🏗️ <b>Grand Projet !</b> Le monstre ne cède le passage qu’à un vrai programme complet. Assemble tout le chapitre : <code>print()</code>, la concaténation <code>+</code> et la répétition <code>*</code>.</p><pre>print("=" * 5)   # =====</pre>',
 task:'<b>Mission :</b> affiche une bannière de 3 lignes — une ligne de 20 signes <code>=</code> (fabriquée avec <code>*</code>), la ligne <code>BIENVENUE A PYQUEST</code>, puis encore la ligne de 20 <code>=</code>. Interdit d’écrire les = à la main !',
 starter:'# Ta bannière :\n',forbid:['====='],
 hints:['print("=" * 20) fabrique la ligne complète.','Trois print() : la ligne de =, le texte, puis la ligne de = à nouveau.'],
 solution:'print("=" * 20)\nprint("BIENVENUE A PYQUEST")\nprint("=" * 20)',
 tests:[{out:['====================','BIENVENUE A PYQUEST','====================']}]},

{title:'PROJET · La paie du chasseur',
 lesson:'<p>🏗️ <b>Grand Projet !</b> Le golem exige un vrai calcul de paie : variables, opérations, division entière <code>//</code> et f-string, tout ensemble.</p>',
 task:'<b>Mission :</b> avec les variables déjà données, crée <code>total</code> (chasses × prime + bonus) et <code>semaines</code> (total <code>//</code> 60). Affiche ensuite <code>Total : 125 pièces</code> puis <code>Soit 2 semaines de repos</code> avec des f-strings (les nombres doivent venir des variables !).',
 starter:'chasses = 7\nprime = 15\nbonus = 20\n',
 hints:['total = chasses * prime + bonus, puis semaines = total // 60 (division entière).','print(f"Total : {total} pièces") — respecte exactement le texte.'],
 solution:'chasses = 7\nprime = 15\nbonus = 20\ntotal = chasses * prime + bonus\nsemaines = total // 60\nprint(f"Total : {total} pièces")\nprint(f"Soit {semaines} semaines de repos")',
 tests:[{out:['Total : 125 pièces','Soit 2 semaines de repos'],vars:{total:125,semaines:2}}]},

{title:'PROJET · Le conseiller de combat',
 lesson:'<p>🏗️ <b>Grand Projet !</b> Le Sphinx veut une vraie intelligence de jeu : une chaîne <code>if / elif / else</code> complète avec conditions combinées (<code>and</code>).</p>',
 task:'<b>Mission :</b> écris <code>conseil(pv, potions)</code> qui renvoie : <code>"KO"</code> si pv ≤ 0 · <code>"bois une potion"</code> si pv &lt; 30 ET potions &gt; 0 · <code>"fuis"</code> si pv &lt; 30 (sans potion) · <code>"attaque"</code> sinon.',
 starter:'def conseil(pv, potions):\n    ',
 hints:['L’ordre compte : teste d’abord pv <= 0, puis pv < 30 and potions > 0.','Quatre cas = if / elif / elif / else, chacun avec son return.'],
 solution:'def conseil(pv, potions):\n    if pv <= 0:\n        return "KO"\n    elif pv < 30 and potions > 0:\n        return "bois une potion"\n    elif pv < 30:\n        return "fuis"\n    else:\n        return "attaque"',
 tests:[{call:{fn:'conseil',args:[0,3],want:'KO'}},{call:{fn:'conseil',args:[20,2],want:'bois une potion'}},{call:{fn:'conseil',args:[10,0],want:'fuis'}},{call:{fn:'conseil',args:[80,0],want:'attaque'}}]},

{title:'PROJET · Le camp d’entraînement',
 lesson:'<p>🏗️ <b>Grand Projet !</b> L’Hydre exige un programme d’entraînement complet : une boucle <code>for</code> avec <code>range</code>, un calcul par tour, et une ligne finale hors boucle.</p>',
 task:'<b>Mission :</b> la variable <code>jours</code> existe déjà. Pour chaque jour de 1 à <code>jours</code>, affiche <code>Jour X : Y pompes</code> où Y = X × 10. Après la boucle, affiche <code>Prêt !</code>',
 starter:'# la variable jours existe déjà\n',
 hints:['for i in range(1, jours + 1): — range s’arrête juste avant la fin.','Dans la boucle : print(f"Jour {i} : {i * 10} pompes"). Le print("Prêt !") est APRÈS (sans indentation).'],
 solution:'for i in range(1, jours + 1):\n    print(f"Jour {i} : {i * 10} pompes")\nprint("Prêt !")',
 tests:[{pre:{jours:3},out:['Jour 1 : 10 pompes','Jour 2 : 20 pompes','Jour 3 : 30 pompes','Prêt !']},{pre:{jours:1},out:['Jour 1 : 10 pompes','Prêt !']}]},

{title:'PROJET · Le maître du sac',
 lesson:'<p>🏗️ <b>Grand Projet !</b> Le Serpent garde l’inventaire du héros : deux fonctions qui manipulent une liste — ajout, test d’appartenance, retrait.</p>',
 task:'<b>Mission :</b> écris <code>ranger(sac, objet)</code> qui ajoute l’objet au sac et renvoie le nouveau nombre d’objets, et <code>jeter(sac, objet)</code> qui retire l’objet et renvoie <code>True</code> s’il était dans le sac, sinon renvoie <code>False</code> sans rien toucher.',
 starter:'def ranger(sac, objet):\n    \n\ndef jeter(sac, objet):\n    ',
 hints:['ranger : sac.append(objet) puis return len(sac).','jeter : if objet in sac: → sac.remove(objet) et return True. Sinon return False.'],
 solution:'def ranger(sac, objet):\n    sac.append(objet)\n    return len(sac)\n\ndef jeter(sac, objet):\n    if objet in sac:\n        sac.remove(objet)\n        return True\n    return False',
 tests:[{call:{fn:'ranger',args:[['pain','corde'],'épée'],want:3}},{call:{fn:'ranger',args:[[],'carte'],want:1}},{call:{fn:'jeter',args:[['pain','corde'],'pain'],want:true}},{call:{fn:'jeter',args:[['pain'],'gemme'],want:false}}]},

{title:'PROJET · La caisse du marchand',
 lesson:'<p>🏗️ <b>Grand Projet !</b> Le Gardien tient la boutique : parcours un panier (liste) et additionne les prix lus dans un dictionnaire. <code>.get(cle, 0)</code> évite le crash si l’objet est inconnu.</p>',
 task:'<b>Mission :</b> écris <code>facture(panier, prix)</code> qui renvoie le total du panier. Chaque objet du panier coûte <code>prix[objet]</code> ; un objet absent du dictionnaire coûte 0 (utilise <code>.get</code>).',
 starter:'def facture(panier, prix):\n    ',
 hints:['total = 0, puis for objet in panier: total = total + prix.get(objet, 0)','N’oublie pas return total après la boucle.'],
 solution:'def facture(panier, prix):\n    total = 0\n    for objet in panier:\n        total = total + prix.get(objet, 0)\n    return total',
 tests:[{call:{fn:'facture',args:[['épée','potion'],{__dict__:{'épée':100,potion:30}}],want:130}},{call:{fn:'facture',args:[['épée','caillou'],{__dict__:{'épée':100,potion:30}}],want:100}},{call:{fn:'facture',args:[[],{__dict__:{potion:30}}],want:0}}]},

{title:'PROJET · La forge des sorts',
 lesson:'<p>🏗️ <b>Grand Projet !</b> L’Archimage forge des sorts en chaîne : une fonction qui en appelle une autre, et un paramètre par défaut. C’est comme ça qu’on assemble un vrai programme.</p>',
 task:'<b>Mission :</b> écris <code>puissance(niveau)</code> qui renvoie <code>niveau * 5 + 10</code>, puis <code>sort(nom, niveau=1)</code> qui renvoie <code>&lt;nom&gt; inflige &lt;X&gt; dégâts</code> où X vient de <code>puissance(niveau)</code>.',
 starter:'def puissance(niveau):\n    \n\ndef sort(nom, niveau=1):\n    ',
 hints:['sort doit APPELER puissance : f"{nom} inflige {puissance(niveau)} dégâts"','Le paramètre par défaut s’écrit def sort(nom, niveau=1):'],
 solution:'def puissance(niveau):\n    return niveau * 5 + 10\n\ndef sort(nom, niveau=1):\n    return f"{nom} inflige {puissance(niveau)} dégâts"',
 tests:[{call:{fn:'puissance',args:[4],want:30}},{call:{fn:'sort',args:['Boule de feu',4],want:'Boule de feu inflige 30 dégâts'}},{call:{fn:'sort',args:['Étincelle'],want:'Étincelle inflige 15 dégâts'}}]},

{title:'PROJET · Ton familier de compagnie',
 lesson:'<p>🏗️ <b>Grand Projet de fin d’acte !</b> Le Dragon exige une classe complète : constructeur, attributs, et deux méthodes dont une qui protège une limite avec <code>min()</code>.</p>',
 task:'<b>Mission :</b> complète la classe <code>Familier</code> : <code>__init__</code> garde le nom et met <code>pv</code> à 20 · <code>cri()</code> renvoie <code>&lt;nom&gt; rugit !</code> · <code>manger()</code> ajoute 5 PV sans jamais dépasser 30. Sortie attendue : le cri, 25, 30.',
 starter:'class Familier:\n    def __init__(self, nom):\n        pass  # ← garde nom, et pv = 20\n\n    def cri(self):\n        pass  # ← renvoie "<nom> rugit !"\n\n    def manger(self):\n        pass  # ← +5 PV, maximum 30\n\n# --- scénario de test (ne modifie pas) ---\nf = Familier("Pyro")\nprint(f.cri())\nf.manger()\nprint(f.pv)\nf.manger()\nf.manger()\nprint(f.pv)',
 hints:['Dans __init__ : self.nom = nom et self.pv = 20.','manger : self.pv = min(30, self.pv + 5)'],
 solution:'class Familier:\n    def __init__(self, nom):\n        self.nom = nom\n        self.pv = 20\n\n    def cri(self):\n        return f"{self.nom} rugit !"\n\n    def manger(self):\n        self.pv = min(30, self.pv + 5)\n\n# --- scénario de test (ne modifie pas) ---\nf = Familier("Pyro")\nprint(f.cri())\nf.manger()\nprint(f.pv)\nf.manger()\nf.manger()\nprint(f.pv)',
 tests:[{out:['Pyro rugit !','25','30']}]},

{title:'PROJET · L’équipe du fil rouge',
 lesson:'<p>🏗️ <b>Grand Projet !</b> Ton RPG s’agrandit : fabrique une équipe entière (liste de dictionnaires) et calcule ses PV totaux. Les vraies données de jeu ressemblent exactement à ça.</p>',
 task:'<b>Mission :</b> écris <code>creer_equipe(noms)</code> qui renvoie une liste de persos <code>{"nom": ..., "pv": 100}</code> (un par nom), et <code>pv_total(equipe)</code> qui renvoie la somme des <code>"pv"</code> de l’équipe.',
 starter:'def creer_equipe(noms):\n    \n\ndef pv_total(equipe):\n    ',
 hints:['creer_equipe : une compréhension [{"nom": n, "pv": 100} for n in noms] ou une boucle avec append.','pv_total : total = 0, puis for p in equipe: total = total + p["pv"]'],
 solution:'def creer_equipe(noms):\n    return [{"nom": n, "pv": 100} for n in noms]\n\ndef pv_total(equipe):\n    total = 0\n    for p in equipe:\n        total = total + p["pv"]\n    return total',
 tests:[{call:{fn:'creer_equipe',args:[['Ayla','Bram']],want:[{__dict__:{nom:'Ayla',pv:100}},{__dict__:{nom:'Bram',pv:100}}]}},{call:{fn:'creer_equipe',args:[[]],want:[]}},{call:{fn:'pv_total',args:[[{__dict__:{nom:'A',pv:40}},{__dict__:{nom:'B',pv:25}}]],want:65}},{call:{fn:'pv_total',args:[[]],want:0}}]},

{title:'PROJET · Le tri des parchemins',
 lesson:'<p>🏗️ <b>Grand Projet !</b> La Veuve a mélangé de vrais nombres et des parchemins corrompus. Un programme robuste convertit ce qu’il peut et ignore le reste — <code>try/except</code> DANS une boucle.</p>',
 task:'<b>Mission :</b> écris <code>convertir(textes)</code> qui renvoie la liste des textes convertis en nombres avec <code>int()</code>, en ignorant ceux qui échouent (ValueError). Puis <code>division_sure(a, b)</code> qui renvoie <code>a / b</code>, ou <code>None</code> si b vaut 0.',
 starter:'def convertir(textes):\n    \n\ndef division_sure(a, b):\n    ',
 hints:['Dans la boucle : try: resultat.append(int(t)) — except ValueError: pass','division_sure : try: return a / b — except ZeroDivisionError: return None'],
 solution:'def convertir(textes):\n    resultat = []\n    for t in textes:\n        try:\n            resultat.append(int(t))\n        except ValueError:\n            pass\n    return resultat\n\ndef division_sure(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return None',
 tests:[{call:{fn:'convertir',args:[['1','x','3']],want:[1,3]}},{call:{fn:'convertir',args:[['abc']],want:[]}},{call:{fn:'division_sure',args:[10,2],want:5}},{call:{fn:'division_sure',args:[5,0],want:null}}]},

{title:'PROJET · Le scribe royal',
 lesson:'<p>🏗️ <b>Grand Projet !</b> Le Tisseur te confie les textes du royaume : censure et initiales, avec les méthodes de chaînes enchaînées (<code>replace</code>, <code>split</code>, <code>upper</code>) et l’indexation.</p>',
 task:'<b>Mission :</b> écris <code>censurer(phrase, interdit)</code> qui remplace le mot interdit par <code>***</code>, et <code>initiales(nom)</code> qui renvoie la première lettre de chaque mot, en MAJUSCULE, collées (ex : <code>ada lovelace</code> → <code>AL</code>).',
 starter:'def censurer(phrase, interdit):\n    \n\ndef initiales(nom):\n    ',
 hints:['censurer : return phrase.replace(interdit, "***")','initiales : nom.split() donne les mots, m[0].upper() la première lettre — accumule dans une chaîne.'],
 solution:'def censurer(phrase, interdit):\n    return phrase.replace(interdit, "***")\n\ndef initiales(nom):\n    resultat = ""\n    for m in nom.split():\n        resultat = resultat + m[0].upper()\n    return resultat',
 tests:[{call:{fn:'censurer',args:['le dragon dort','dragon'],want:'le *** dort'}},{call:{fn:'censurer',args:['rien à cacher','x'],want:'rien à cacher'}},{call:{fn:'initiales',args:['ada lovelace'],want:'AL'}},{call:{fn:'initiales',args:['jean claude van damme'],want:'JCVD'}}]},

{title:'PROJET · Le grand tri alchimique',
 lesson:'<p>🏗️ <b>Grand Projet !</b> L’Alchimiste veut TOUT en compréhensions : un filtre et une transformation, en deux lignes élégantes. <code>.append</code> est banni de son laboratoire.</p>',
 task:'<b>Mission :</b> les listes <code>forces</code> et <code>noms</code> existent déjà. Crée <code>fortes</code> (les forces ≥ 50) et <code>etiquettes</code> (les noms en MAJUSCULES), chacune avec une compréhension, puis affiche <code>fortes</code> puis <code>etiquettes</code>.',
 starter:'# forces et noms existent déjà\n',forbid:['.append'],
 hints:['fortes = [x for x in forces if x >= 50]','etiquettes = [n.upper() for n in noms] — puis deux print().'],
 solution:'fortes = [x for x in forces if x >= 50]\netiquettes = [n.upper() for n in noms]\nprint(fortes)\nprint(etiquettes)',
 tests:[{pre:{forces:[10,60,35,80],noms:['roc','lave']},out:['[60, 80]',"['ROC', 'LAVE']"]},{pre:{forces:[5],noms:['brume']},out:['[]',"['BRUME']"]}]},

{title:'PROJET · La finale du tournoi',
 lesson:'<p>🏗️ <b>Grand Projet !</b> Le Duelliste pose LA question d’entretien : le deuxième plus grand. Il faut garder DEUX champions à jour en un seul passage — <code>max</code>, <code>sorted</code> et <code>.sort</code> sont interdits.</p>',
 task:'<b>Mission :</b> écris <code>deuxieme(liste)</code> qui renvoie le deuxième plus grand élément (la liste a toujours au moins 2 éléments). Interdits : <code>max</code>, <code>sorted</code>, <code>.sort</code>.',
 starter:'def deuxieme(liste):\n    ',forbid:['max','sorted','.sort'],
 hints:['Commence avec les 2 premiers : le plus grand devient champion, l’autre second.','Pour chaque x suivant : si x > champion → le champion devient second et x champion ; sinon si x > second → x devient second.'],
 solution:'def deuxieme(liste):\n    if liste[0] > liste[1]:\n        champion = liste[0]\n        second = liste[1]\n    else:\n        champion = liste[1]\n        second = liste[0]\n    for x in liste[2:]:\n        if x > champion:\n            second = champion\n            champion = x\n        elif x > second:\n            second = x\n    return second',
 tests:[{call:{fn:'deuxieme',args:[[3,9,5]],want:5}},{call:{fn:'deuxieme',args:[[10,2]],want:2}},{call:{fn:'deuxieme',args:[[1,2,3,4]],want:3}},{hidden:true,call:{fn:'deuxieme',args:[[5,1,9,8]],want:8}}]},

{title:'PROJET · L’armée des créatures',
 lesson:'<p>🏗️ <b>Grand Projet !</b> La Lignée exige l’héritage complet : une classe fille qui <b>redéfinit</b> une méthode du parent et en <b>ajoute</b> une nouvelle — tout en héritant du <code>__init__</code>.</p>',
 task:'<b>Mission :</b> complète <code>Dragon(Creature)</code> : redéfinis <code>crier()</code> pour renvoyer <code>&lt;nom&gt; crache du FEU</code>, et ajoute <code>voler()</code> qui renvoie <code>&lt;nom&gt; prend son envol</code>. Sortie attendue : Gob grogne, Smaug crache du FEU, Smaug prend son envol, 30.',
 starter:'class Creature:\n    def __init__(self, nom):\n        self.nom = nom\n        self.pv = 30\n\n    def crier(self):\n        return f"{self.nom} grogne"\n\nclass Dragon(Creature):\n    pass  # ← redéfinis crier(), ajoute voler()\n\n# --- scénario (ne modifie pas) ---\nc = Creature("Gob")\nd = Dragon("Smaug")\nprint(c.crier())\nprint(d.crier())\nprint(d.voler())\nprint(d.pv)',
 hints:['Dans Dragon, écris une nouvelle méthode crier(self) : elle remplace celle du parent.','Dragon n’a pas besoin de __init__ : il hérite de celui de Creature (d.pv vaut donc 30). Enlève le pass !'],
 solution:'class Creature:\n    def __init__(self, nom):\n        self.nom = nom\n        self.pv = 30\n\n    def crier(self):\n        return f"{self.nom} grogne"\n\nclass Dragon(Creature):\n    def crier(self):\n        return f"{self.nom} crache du FEU"\n\n    def voler(self):\n        return f"{self.nom} prend son envol"\n\n# --- scénario (ne modifie pas) ---\nc = Creature("Gob")\nd = Dragon("Smaug")\nprint(c.crier())\nprint(d.crier())\nprint(d.voler())\nprint(d.pv)',
 tests:[{out:['Gob grogne','Smaug crache du FEU','Smaug prend son envol','30']}]},

{title:'PROJET · Le service de la taverne',
 lesson:'<p>🏗️ <b>Grand Projet !</b> L’Architecte gère la taverne : une FILE de clients (premier arrivé, premier servi → <code>pop(0)</code>) et une PILE d’assiettes (dernière posée, première lavée → <code>pop()</code>).</p>',
 task:'<b>Mission :</b> écris 3 fonctions — <code>arriver(file, client)</code> : ajoute le client et renvoie la taille de la file · <code>servir(file)</code> : retire et renvoie le PREMIER client · <code>laver(pile)</code> : retire et renvoie la DERNIÈRE assiette.',
 starter:'def arriver(file, client):\n    \n\ndef servir(file):\n    \n\ndef laver(pile):\n    ',
 hints:['File = pop(0) (le premier). Pile = pop() sans argument (le dernier).','arriver : file.append(client) puis return len(file).'],
 solution:'def arriver(file, client):\n    file.append(client)\n    return len(file)\n\ndef servir(file):\n    return file.pop(0)\n\ndef laver(pile):\n    return pile.pop()',
 tests:[{call:{fn:'arriver',args:[['ana'],'ben'],want:2}},{call:{fn:'servir',args:[['ana','ben']],want:'ana'}},{call:{fn:'laver',args:[['a1','a2','a3']],want:'a3'}}]},

{title:'PROJET · La spirale infinie',
 lesson:'<p>🏗️ <b>Grand Projet !</b> Le Miroir interdit toute boucle : uniquement des fonctions qui s’appellent elles-mêmes. Chaque récursion a un <b>cas de base</b> (l’arrêt) et un <b>cas récursif</b> (le rappel).</p>',
 task:'<b>Mission :</b> écris <code>somme_recursive(n)</code> (la somme 1+2+…+n, 0 si n ≤ 0) et <code>puissance(base, n)</code> (base multipliée n fois, 1 si n = 0) — toutes deux SANS boucle (for et while interdits).',
 starter:'def somme_recursive(n):\n    \n\ndef puissance(base, n):\n    ',forbid:['for ','while '],
 hints:['somme_recursive : if n <= 0: return 0 — sinon return n + somme_recursive(n - 1)','puissance : if n == 0: return 1 — sinon return base * puissance(base, n - 1)'],
 solution:'def somme_recursive(n):\n    if n <= 0:\n        return 0\n    return n + somme_recursive(n - 1)\n\ndef puissance(base, n):\n    if n == 0:\n        return 1\n    return base * puissance(base, n - 1)',
 tests:[{call:{fn:'somme_recursive',args:[5],want:15}},{call:{fn:'somme_recursive',args:[0],want:0}},{call:{fn:'puissance',args:[2,10],want:1024}},{call:{fn:'puissance',args:[7,0],want:1}},{hidden:true,call:{fn:'somme_recursive',args:[100],want:5050}}]},

{title:'PROJET · L’épreuve du Juge',
 lesson:'<p>🏗️ <b>Grand Projet !</b> Deux classiques d’entretien, jugés sur des tests cachés 🎭. Les anagrammes : deux mots faits des mêmes lettres. La compression : <code>aaabb</code> → <code>a3b2</code>.</p>',
 task:'<b>Mission :</b> écris <code>anagramme(a, b)</code> (True si les deux mots ont exactement les mêmes lettres, majuscules ignorées) et <code>compresser(mot)</code> (chaque lettre suivie de son nombre de répétitions ; <code>""</code> renvoie <code>""</code>).',
 starter:'def anagramme(a, b):\n    \n\ndef compresser(mot):\n    ',
 hints:['anagramme : sorted(a.lower()) == sorted(b.lower()) — sorted trie les lettres d’un mot.','compresser : garde la lettre courante et un compteur ; quand la lettre change, ajoute lettre + str(compteur) au résultat. Pense au mot vide et à la DERNIÈRE série !'],
 solution:'def anagramme(a, b):\n    return sorted(a.lower()) == sorted(b.lower())\n\ndef compresser(mot):\n    if mot == "":\n        return ""\n    resultat = ""\n    courante = mot[0]\n    compte = 1\n    for lettre in mot[1:]:\n        if lettre == courante:\n            compte = compte + 1\n        else:\n            resultat = resultat + courante + str(compte)\n            courante = lettre\n            compte = 1\n    return resultat + courante + str(compte)',
 tests:[{call:{fn:'anagramme',args:['Chien','niche'],want:true}},{call:{fn:'anagramme',args:['chat','chien'],want:false}},{call:{fn:'compresser',args:['aaabb'],want:'a3b2'}},{call:{fn:'compresser',args:['abc'],want:'a1b1c1'}},{hidden:true,call:{fn:'compresser',args:[''],want:''}},{hidden:true,call:{fn:'compresser',args:['zzzzzzzzzz'],want:'z10'}},{hidden:true,call:{fn:'anagramme',args:['a','ab'],want:false}}]},

{title:'PROJET FINAL · Ton RPG complet',
 lesson:'<p>🏗️ <b>LE GRAND PROJET FINAL !</b> Tout ce que tu as appris en un seul programme : classes, attributs, listes, conditions, <code>min</code>/<code>max</code>, f-strings. Termine le moteur de ton RPG — c’est TON jeu maintenant.</p>',
 task:'<b>Mission finale :</b> complète la classe <code>Heros</code> : <code>__init__</code> (nom, force, pv = 100, sac = liste vide) · <code>ramasser(objet)</code> ajoute au sac · <code>boire()</code> : si <code>"potion"</code> est dans le sac, la retire, rend +30 PV (max 100) et renvoie True, sinon False · <code>attaquer(cible)</code> : retire <code>force</code> aux PV de la cible (min 0) et renvoie <code>&lt;nom&gt; inflige &lt;force&gt; dégâts à &lt;cible&gt;</code>.',
 starter:'class Monstre:\n    def __init__(self, nom, pv):\n        self.nom = nom\n        self.pv = pv\n\nclass Heros:\n    def __init__(self, nom, force):\n        pass  # ← nom, force, pv = 100, sac = []\n\n    def ramasser(self, objet):\n        pass  # ← ajoute l\'objet au sac\n\n    def boire(self):\n        pass  # ← potion dans le sac ? retire-la, +30 PV (max 100), True. Sinon False\n\n    def attaquer(self, cible):\n        pass  # ← -force aux PV de cible (min 0), renvoie le message\n\n# --- scénario final (ne modifie pas) ---\nh = Heros("Nova", 25)\nm = Monstre("Ombre", 60)\nprint(h.attaquer(m))\nprint(m.pv)\nh.pv = 40\nh.ramasser("potion")\nprint(h.boire())\nprint(h.pv)\nprint(h.boire())',
 hints:['boire : if "potion" in self.sac: → self.sac.remove("potion"), self.pv = min(100, self.pv + 30), return True. Sinon return False.','attaquer : cible.pv = max(0, cible.pv - self.force) puis return f"{self.nom} inflige {self.force} dégâts à {cible.nom}"'],
 solution:'class Monstre:\n    def __init__(self, nom, pv):\n        self.nom = nom\n        self.pv = pv\n\nclass Heros:\n    def __init__(self, nom, force):\n        self.nom = nom\n        self.force = force\n        self.pv = 100\n        self.sac = []\n\n    def ramasser(self, objet):\n        self.sac.append(objet)\n\n    def boire(self):\n        if "potion" in self.sac:\n            self.sac.remove("potion")\n            self.pv = min(100, self.pv + 30)\n            return True\n        return False\n\n    def attaquer(self, cible):\n        cible.pv = max(0, cible.pv - self.force)\n        return f"{self.nom} inflige {self.force} dégâts à {cible.nom}"\n\n# --- scénario final (ne modifie pas) ---\nh = Heros("Nova", 25)\nm = Monstre("Ombre", 60)\nprint(h.attaquer(m))\nprint(m.pv)\nh.pv = 40\nh.ramasser("potion")\nprint(h.boire())\nprint(h.pv)\nprint(h.boire())',
 tests:[{out:['Nova inflige 25 dégâts à Ombre','35','True','70','False']}]}
];
PROJETS.forEach((p,i)=>{CHAPTERS[i].projet=p;});
window.PYQUEST_BASE={actes:ACTES,chapters:CHAPTERS};
})();
