/* ============================================================
   PyQuest — extensions hebdomadaires.
   L'agent ajoute chaque semaine UN bloc PYQUEST_EXTENSIONS.push({...})
   À LA FIN de ce fichier, sans toucher aux blocs précédents.
   Format d'un bloc : voir le premier bloc ci-dessous (modèle canonique).
   Valider avec :  node tools/validate.js
   ============================================================ */
window.PYQUEST_EXTENSIONS = window.PYQUEST_EXTENSIONS || [];

/* ============ SEMAINE DU 2026-07-20 — Acte IV ============ */
window.PYQUEST_EXTENSIONS.push({
 dispo:'2026-07-20',
 name:'Acte IV — Les Marais de la Mémoire',sub:'Semaine 4 · compter, fusionner, quadriller',dmg:24,xp:25,tick:10,
 chapters:[
 {jour:'Semaine 4',emoji:'🐸',name:'Le Crapaud Compteur',mini:'dictionnaires de comptage',
  desc:'Il compte tout ce qui bouge dans le marais. Le pattern de comptage est PARTOUT dans le vrai code.',
  challenges:[
   {title:'Le comptage',
    lesson:'<p>LE pattern à connaître : compter les occurrences avec un dictionnaire. <code>d.get(x, 0)</code> renvoie 0 si la clé n’existe pas encore :</p><pre>d[x] = d.get(x, 0) + 1</pre>',
    task:'<b>Mission :</b> écris <code>compter(liste)</code> qui renvoie un dictionnaire {élément: nombre d’apparitions}.',
    starter:'def compter(liste):\n    ',
    hints:['Commence avec d = {} puis boucle sur la liste.','À chaque tour : d[x] = d.get(x, 0) + 1 — puis return d.'],
    solution:'def compter(liste):\n    d = {}\n    for x in liste:\n        d[x] = d.get(x, 0) + 1\n    return d',
    tests:[{call:{fn:'compter',args:[['a','b','a']],want:{__dict__:{a:2,b:1}}}},{call:{fn:'compter',args:[[]],want:{__dict__:{}}}},{call:{fn:'compter',args:[['ver','ver','ver']],want:{__dict__:{ver:3}}}}]},
   {title:'Le plus fréquent',
    lesson:'<p>Pour trouver la clé qui a la plus grande valeur, on parcourt les paires avec <code>d.items()</code> :</p><pre>for cle, valeur in d.items():</pre><p>et on garde un champion, comme d’habitude.</p>',
    task:'<b>Mission :</b> écris <code>plus_frequent(d)</code> qui renvoie la CLÉ dont la valeur est la plus grande (d n’est jamais vide).',
    starter:'def plus_frequent(d):\n    ',
    hints:['meilleur = None et haut = -1 avant la boucle.','for cle, valeur in d.items(): — si valeur > haut, mets à jour les deux.'],
    solution:'def plus_frequent(d):\n    meilleur = None\n    haut = -1\n    for cle, valeur in d.items():\n        if valeur > haut:\n            haut = valeur\n            meilleur = cle\n    return meilleur',
    tests:[{call:{fn:'plus_frequent',args:[{__dict__:{a:2,b:5}}],want:'b'}},{call:{fn:'plus_frequent',args:[{__dict__:{x:1}}],want:'x'}}]},
   {title:'La fusion des inventaires',
    lesson:'<p>Fusionner deux dictionnaires de comptage : on verse le second dans le premier en ADDITIONNANT les valeurs — encore le pattern <code>get(cle, 0)</code>.</p>',
    task:'<b>Mission :</b> écris <code>fusionner(d1, d2)</code> qui ajoute chaque paire de d2 dans d1 (en additionnant si la clé existe déjà) et renvoie d1.',
    starter:'def fusionner(d1, d2):\n    ',
    hints:['for cle, valeur in d2.items():','d1[cle] = d1.get(cle, 0) + valeur — puis return d1 après la boucle.'],
    solution:'def fusionner(d1, d2):\n    for cle, valeur in d2.items():\n        d1[cle] = d1.get(cle, 0) + valeur\n    return d1',
    tests:[{call:{fn:'fusionner',args:[{__dict__:{or:2}},{__dict__:{or:3,bois:1}}],want:{__dict__:{or:5,bois:1}}}},{call:{fn:'fusionner',args:[{__dict__:{}},{__dict__:{a:1}}],want:{__dict__:{a:1}}}}]}],
  projet:{title:'PROJET · Le recensement du marais',
    lesson:'<p>🏗️ <b>Grand Projet !</b> Le Crapaud exige le recensement complet : compter les créatures PUIS produire un rapport trié — les deux patterns du chapitre bout à bout.</p>',
    task:'<b>Mission :</b> écris <code>recensement(creatures)</code> (liste → dictionnaire de comptage) et <code>rapport(d)</code> qui renvoie la liste des lignes <code>nom x N</code>, triées par nom (parcours <code>sorted(d.keys())</code>).',
    starter:'def recensement(creatures):\n    \n\ndef rapport(d):\n    ',
    hints:['recensement : le pattern d[x] = d.get(x, 0) + 1.','rapport : lignes = [] puis for nom in sorted(d.keys()): lignes.append(f"{nom} x {d[nom]}")'],
    solution:'def recensement(creatures):\n    d = {}\n    for x in creatures:\n        d[x] = d.get(x, 0) + 1\n    return d\n\ndef rapport(d):\n    lignes = []\n    for nom in sorted(d.keys()):\n        lignes.append(f"{nom} x {d[nom]}")\n    return lignes',
    tests:[{call:{fn:'recensement',args:[['grenouille','moustique','grenouille']],want:{__dict__:{grenouille:2,moustique:1}}}},{call:{fn:'rapport',args:[{__dict__:{moustique:3,grenouille:2}}],want:['grenouille x 2','moustique x 3']}},{hidden:true,call:{fn:'rapport',args:[{__dict__:{}}],want:[]}},{hidden:true,call:{fn:'recensement',args:[[]],want:{__dict__:{}}}}]}},
 {jour:'Semaine 4',emoji:'🦉',name:'La Chouette des Matrices',mini:'listes de listes',
  desc:'Elle voit le monde en grilles : plateaux de jeu, images, tableaux — tout est liste de listes.',
  challenges:[
   {title:'La grille',
    lesson:'<p>Une <b>liste de listes</b> représente une grille : <code>grille[ligne][colonne]</code>.</p><pre>g = [[1, 2], [3, 4]]\ng[1][0]   # 3 (ligne 1, colonne 0)</pre>',
    task:'<b>Mission :</b> écris <code>case(grille, ligne, col)</code> qui renvoie la valeur à cette position.',
    starter:'def case(grille, ligne, col):\n    ',
    hints:['Deux paires de crochets à la suite.','return grille[ligne][col]'],
    solution:'def case(grille, ligne, col):\n    return grille[ligne][col]',
    tests:[{call:{fn:'case',args:[[[1,2],[3,4]],1,0],want:3}},{call:{fn:'case',args:[[['x']],0,0],want:'x'}}]},
   {title:'La somme du plateau',
    lesson:'<p>Pour visiter TOUTES les cases : une boucle dans une boucle.</p><pre>for ligne in grille:\n    for valeur in ligne:\n        ...</pre>',
    task:'<b>Mission :</b> écris <code>somme_grille(grille)</code> qui renvoie la somme de toutes les cases, avec une double boucle (sum() interdit).',
    starter:'def somme_grille(grille):\n    ',forbid:['sum'],
    hints:['total = 0 avant les boucles.','for ligne in grille: puis for v in ligne: total = total + v'],
    solution:'def somme_grille(grille):\n    total = 0\n    for ligne in grille:\n        for v in ligne:\n            total = total + v\n    return total',
    tests:[{call:{fn:'somme_grille',args:[[[1,2],[3,4]]],want:10}},{call:{fn:'somme_grille',args:[[[5]]],want:5}},{call:{fn:'somme_grille',args:[[[]]],want:0}}]},
   {title:'La diagonale',
    lesson:'<p>La diagonale d’une grille carrée : la case <code>[i][i]</code> pour chaque i. Avec <code>range(len(grille))</code> tu obtiens tous les indices.</p>',
    task:'<b>Mission :</b> écris <code>diagonale(grille)</code> qui renvoie la liste des cases [0][0], [1][1], [2][2]…',
    starter:'def diagonale(grille):\n    ',
    hints:['Une compréhension fait tout : [... for i in range(len(grille))]','return [grille[i][i] for i in range(len(grille))]'],
    solution:'def diagonale(grille):\n    return [grille[i][i] for i in range(len(grille))]',
    tests:[{call:{fn:'diagonale',args:[[[1,2],[3,4]]],want:[1,4]}},{call:{fn:'diagonale',args:[[[7]]],want:[7]}},{call:{fn:'diagonale',args:[[]],want:[]}}]}],
  projet:{title:'PROJET · La carte au trésor',
    lesson:'<p>🏗️ <b>Grand Projet !</b> La Chouette a caché un trésor dans sa grille. Il faut le LOCALISER : parcourir avec les INDICES (<code>range(len(...))</code>) pour renvoyer la position, pas la valeur.</p>',
    task:'<b>Mission :</b> écris <code>chercher(grille, tresor)</code> qui renvoie la position <code>[ligne, colonne]</code> de la première apparition du trésor, ou <code>[-1, -1]</code> s’il est absent.',
    starter:'def chercher(grille, tresor):\n    ',
    hints:['for i in range(len(grille)): puis for j in range(len(grille[i])):','if grille[i][j] == tresor: return [i, j] — et [-1, -1] tout à la fin.'],
    solution:'def chercher(grille, tresor):\n    for i in range(len(grille)):\n        for j in range(len(grille[i])):\n            if grille[i][j] == tresor:\n                return [i, j]\n    return [-1, -1]',
    tests:[{call:{fn:'chercher',args:[[['.','.'],['.','X']],'X'],want:[1,1]}},{call:{fn:'chercher',args:[[['.','.']],'X'],want:[-1,-1]}},{hidden:true,call:{fn:'chercher',args:[[['X']],'X'],want:[0,0]}},{hidden:true,call:{fn:'chercher',args:[[],'X'],want:[-1,-1]}}]}}
]});

/* ============ SEMAINE DU 2026-07-27 — Acte V ============ */
window.PYQUEST_EXTENSIONS.push({
 dispo:'2026-07-27',
 name:'Acte V — Les Pics du Tri',sub:'Semaine 5 · trier et chercher comme une machine',dmg:25,xp:26,tick:10,
 chapters:[
 {jour:'Semaine 5',emoji:'🏔️',name:'Le Géant Trieur',mini:'tri par sélection',
  desc:'Il range la montagne caillou par caillou : trouve le plus petit, mets-le devant, recommence.',
  challenges:[
   {title:'Le plus petit caillou',
    lesson:'<p>Première brique du tri : trouver la POSITION du plus petit élément — on garde l’indice du champion, pas sa valeur :</p><pre>best = 0\npour chaque i : si liste[i] &lt; liste[best] : best = i</pre>',
    task:'<b>Mission :</b> écris <code>indice_petit(liste)</code> qui renvoie la position du plus petit élément (min, sorted et .sort interdits).',
    starter:'def indice_petit(liste):\n    ',forbid:['min','sorted','.sort'],
    hints:['best = 0 puis boucle for i in range(1, len(liste)):','if liste[i] < liste[best]: best = i — et return best à la fin.'],
    solution:'def indice_petit(liste):\n    best = 0\n    for i in range(1, len(liste)):\n        if liste[i] < liste[best]:\n            best = i\n    return best',
    tests:[{call:{fn:'indice_petit',args:[[5,2,8]],want:1}},{call:{fn:'indice_petit',args:[[1,2,3]],want:0}},{call:{fn:'indice_petit',args:[[9]],want:0}}]},
   {title:'L’échange',
    lesson:'<p>Deuxième brique : échanger deux cases d’une liste. Il faut une variable TEMPORAIRE pour ne pas écraser :</p><pre>t = liste[i]\nliste[i] = liste[j]\nliste[j] = t</pre>',
    task:'<b>Mission :</b> écris <code>echanger(liste, i, j)</code> qui échange les cases i et j puis renvoie la liste.',
    starter:'def echanger(liste, i, j):\n    ',
    hints:['Trois lignes : t = liste[i], puis liste[i] = liste[j], puis liste[j] = t.','N’oublie pas return liste.'],
    solution:'def echanger(liste, i, j):\n    t = liste[i]\n    liste[i] = liste[j]\n    liste[j] = t\n    return liste',
    tests:[{call:{fn:'echanger',args:[['a','b','c'],0,2],want:['c','b','a']}},{call:{fn:'echanger',args:[[1,2],0,1],want:[2,1]}}]},
   {title:'Le premier pas du tri',
    lesson:'<p>Troisième brique : mettre le plus petit élément EN PREMIÈRE position — trouve son indice, échange-le avec la case 0. C’est exactement un tour du tri par sélection.</p>',
    task:'<b>Mission :</b> écris <code>premier_pas(liste)</code> qui place le plus petit élément en position 0 (échange) et renvoie la liste (min, sorted, .sort interdits).',
    starter:'def premier_pas(liste):\n    ',forbid:['min','sorted','.sort'],
    hints:['Retrouve d’abord l’indice du plus petit (comme la dalle 1).','Puis échange les cases 0 et best avec une variable temporaire.'],
    solution:'def premier_pas(liste):\n    best = 0\n    for i in range(1, len(liste)):\n        if liste[i] < liste[best]:\n            best = i\n    t = liste[0]\n    liste[0] = liste[best]\n    liste[best] = t\n    return liste',
    tests:[{call:{fn:'premier_pas',args:[[5,2,8]],want:[2,5,8]}},{call:{fn:'premier_pas',args:[[1,3]],want:[1,3]}}]}],
  projet:{title:'PROJET · Le grand tri du Géant',
    lesson:'<p>🏗️ <b>Grand Projet !</b> Le tri par sélection complet : pour chaque position i, trouve le plus petit dans le reste de la liste et échange-le avec la case i. Deux boucles imbriquées — LE classique absolu des entretiens.</p>',
    task:'<b>Mission :</b> écris <code>tri_selection(liste)</code> qui trie la liste en place et la renvoie. Interdits : <code>sorted</code>, <code>.sort</code>, <code>min</code>.',
    starter:'def tri_selection(liste):\n    ',forbid:['sorted','.sort','min'],
    hints:['for i in range(len(liste)): puis cherche best entre i et la fin (range(i + 1, len(liste))).','Après la boucle interne : échange liste[i] et liste[best] avec une variable temporaire.'],
    solution:'def tri_selection(liste):\n    for i in range(len(liste)):\n        best = i\n        for j in range(i + 1, len(liste)):\n            if liste[j] < liste[best]:\n                best = j\n        t = liste[i]\n        liste[i] = liste[best]\n        liste[best] = t\n    return liste',
    tests:[{call:{fn:'tri_selection',args:[[3,1,2]],want:[1,2,3]}},{call:{fn:'tri_selection',args:[[5,4,3,2,1]],want:[1,2,3,4,5]}},{hidden:true,call:{fn:'tri_selection',args:[[]],want:[]}},{hidden:true,call:{fn:'tri_selection',args:[[7]],want:[7]}},{hidden:true,call:{fn:'tri_selection',args:[[2,2,1]],want:[1,2,2]}}]}},
 {jour:'Semaine 5',emoji:'🦅',name:'L’Aigle Dichotomique',mini:'recherche binaire',
  desc:'Il ne survole jamais toute la vallée : il coupe l’espace en deux à chaque battement d’ailes.',
  challenges:[
   {title:'Le milieu',
    lesson:'<p>La recherche binaire commence toujours au MILIEU d’une liste triée. La division entière <code>//</code> donne un indice valide :</p><pre>m = len(liste) // 2</pre>',
    task:'<b>Mission :</b> écris <code>milieu(liste)</code> qui renvoie l’élément du milieu (liste jamais vide).',
    starter:'def milieu(liste):\n    ',
    hints:['L’indice du milieu : len(liste) // 2.','return liste[len(liste) // 2]'],
    solution:'def milieu(liste):\n    return liste[len(liste) // 2]',
    tests:[{call:{fn:'milieu',args:[[1,2,3]],want:2}},{call:{fn:'milieu',args:[[1,2,3,4]],want:3}},{call:{fn:'milieu',args:[[9]],want:9}}]},
   {title:'Gauche ou droite ?',
    lesson:'<p>Le cœur de la dichotomie : comparer la cible au milieu. Plus petite → elle est à GAUCHE. Plus grande → à DROITE. On élimine la moitié de la liste d’un coup.</p>',
    task:'<b>Mission :</b> écris <code>direction(liste, cible)</code> qui renvoie <code>"trouve"</code> si l’élément du milieu EST la cible, <code>"gauche"</code> si la cible est plus petite, <code>"droite"</code> sinon.',
    starter:'def direction(liste, cible):\n    ',
    hints:['m = liste[len(liste) // 2] puis trois cas : ==, <, else.','if cible == m: return "trouve" — elif cible < m: return "gauche" — else: return "droite"'],
    solution:'def direction(liste, cible):\n    m = liste[len(liste) // 2]\n    if cible == m:\n        return "trouve"\n    elif cible < m:\n        return "gauche"\n    else:\n        return "droite"',
    tests:[{call:{fn:'direction',args:[[1,5,9],5],want:'trouve'}},{call:{fn:'direction',args:[[1,5,9],2],want:'gauche'}},{call:{fn:'direction',args:[[1,5,9],7],want:'droite'}}]},
   {title:'Le compte des battements',
    lesson:'<p>Pourquoi la dichotomie est si rapide ? Chaque étape DIVISE le problème par 2. Compte les divisions : 1000 éléments → 10 étapes seulement !</p><pre>while n &gt; 1:\n    n = n // 2\n    etapes = etapes + 1</pre>',
    task:'<b>Mission :</b> écris <code>battements(n)</code> qui renvoie combien de fois on peut diviser n par 2 (division entière) avant d’arriver à 1 ou moins.',
    starter:'def battements(n):\n    ',
    hints:['etapes = 0 puis while n > 1:','Dans la boucle : n = n // 2 et etapes = etapes + 1. Return après.'],
    solution:'def battements(n):\n    etapes = 0\n    while n > 1:\n        n = n // 2\n        etapes = etapes + 1\n    return etapes',
    tests:[{call:{fn:'battements',args:[8],want:3}},{call:{fn:'battements',args:[1],want:0}},{call:{fn:'battements',args:[1000],want:9}}]}],
  projet:{title:'PROJET · La chasse de l’Aigle',
    lesson:'<p>🏗️ <b>Grand Projet !</b> La recherche binaire complète : deux bornes <code>gauche</code> et <code>droite</code> qui se resserrent autour de la cible. LA question d’entretien par excellence — et ton premier algorithme en O(log n).</p>',
    task:'<b>Mission :</b> écris <code>recherche_binaire(liste, cible)</code> qui renvoie la POSITION de la cible dans une liste TRIÉE, ou <code>-1</code> si absente. <code>.index</code> interdit.',
    starter:'def recherche_binaire(liste, cible):\n    gauche = 0\n    droite = len(liste) - 1\n    ',forbid:['.index'],
    hints:['while gauche <= droite: — puis m = (gauche + droite) // 2.','Si liste[m] == cible : return m. Si liste[m] < cible : gauche = m + 1. Sinon : droite = m - 1. Et return -1 après la boucle.'],
    solution:'def recherche_binaire(liste, cible):\n    gauche = 0\n    droite = len(liste) - 1\n    while gauche <= droite:\n        m = (gauche + droite) // 2\n        if liste[m] == cible:\n            return m\n        elif liste[m] < cible:\n            gauche = m + 1\n        else:\n            droite = m - 1\n    return -1',
    tests:[{call:{fn:'recherche_binaire',args:[[1,3,5,7,9],7],want:3}},{call:{fn:'recherche_binaire',args:[[1,3,5],4],want:-1}},{hidden:true,call:{fn:'recherche_binaire',args:[[],5],want:-1}},{hidden:true,call:{fn:'recherche_binaire',args:[[2],2],want:0}},{hidden:true,call:{fn:'recherche_binaire',args:[[1,2,3,4,5,6,7,8],1],want:0}},{hidden:true,call:{fn:'recherche_binaire',args:[[1,2,3,4,5,6,7,8],8],want:7}}]}}
]});

/* ============ SEMAINE DU 2026-08-03 — Acte VI ============ */
window.PYQUEST_EXTENSIONS.push({
 dispo:'2026-08-03',
 name:'Acte VI — La Forêt des Mots',sub:'Semaine 6 · maîtriser les textes comme un scribe',dmg:26,xp:27,tick:10,
 chapters:[
 {jour:'Semaine 6',emoji:'🦜',name:'Le Perroquet Palindrome',mini:'chaînes miroir',
  desc:'Il ne répète que les phrases qui se lisent dans les deux sens. kayak. radar. Toi aussi ?',
  challenges:[
   {title:'Le miroir',
    lesson:'<p>Un <b>palindrome</b> se lit pareil dans les deux sens. Méthode : construis l’inverse lettre par lettre (chaque lettre DEVANT), puis compare :</p><pre>inverse = lettre + inverse</pre>',
    task:'<b>Mission :</b> écris <code>est_palindrome(mot)</code> qui renvoie True si le mot est un palindrome, False sinon.',
    starter:'def est_palindrome(mot):\n    ',
    hints:['inverse = "" puis for lettre in mot: inverse = lettre + inverse','return mot == inverse'],
    solution:'def est_palindrome(mot):\n    inverse = ""\n    for lettre in mot:\n        inverse = lettre + inverse\n    return mot == inverse',
    tests:[{call:{fn:'est_palindrome',args:['radar'],want:true}},{call:{fn:'est_palindrome',args:['chat'],want:false}},{call:{fn:'est_palindrome',args:['kayak'],want:true}}]},
   {title:'Le nettoyage',
    lesson:'<p>Avant de tester une PHRASE, il faut la nettoyer : enlever les espaces et tout mettre en minuscules. Les méthodes s’enchaînent :</p><pre>phrase.replace(" ", "").lower()</pre>',
    task:'<b>Mission :</b> écris <code>nettoyer(phrase)</code> qui enlève tous les espaces et met tout en minuscules.',
    starter:'def nettoyer(phrase):\n    ',
    hints:['replace(" ", "") remplace chaque espace par rien.','return phrase.replace(" ", "").lower()'],
    solution:'def nettoyer(phrase):\n    return phrase.replace(" ", "").lower()',
    tests:[{call:{fn:'nettoyer',args:['Esope Reste'],want:'esopereste'}},{call:{fn:'nettoyer',args:['a b c'],want:'abc'}}]},
   {title:'La phrase miroir',
    lesson:'<p>Assemble les deux : nettoie la phrase, PUIS teste le palindrome. « Élu par cette crapule » (sans accents) en est un vrai !</p>',
    task:'<b>Mission :</b> écris <code>phrase_miroir(phrase)</code> : nettoie (espaces + minuscules) puis renvoie True si le résultat est un palindrome.',
    starter:'def phrase_miroir(phrase):\n    ',
    hints:['propre = phrase.replace(" ", "").lower() d’abord.','Puis le test du miroir : construis l’inverse de propre et compare.'],
    solution:'def phrase_miroir(phrase):\n    propre = phrase.replace(" ", "").lower()\n    inverse = ""\n    for lettre in propre:\n        inverse = lettre + inverse\n    return propre == inverse',
    tests:[{call:{fn:'phrase_miroir',args:['elu par cette crapule'],want:true}},{call:{fn:'phrase_miroir',args:['bonjour le monde'],want:false}},{call:{fn:'phrase_miroir',args:['Kayak'],want:true}}]}],
  projet:{title:'PROJET · Le concours du Perroquet',
    lesson:'<p>🏗️ <b>Grand Projet !</b> Le Perroquet organise son concours : parmi une liste de mots, garder les palindromes ET trouver le plus long. Une fonction peut en APPELER une autre — c’est même très encouragé.</p>',
    task:'<b>Mission :</b> écris <code>garder_palindromes(mots)</code> qui renvoie la liste des mots-palindromes (dans l’ordre), et <code>plus_long_palindrome(mots)</code> qui renvoie le palindrome le plus long (le premier en cas d’égalité, <code>""</code> si aucun).',
    starter:'def garder_palindromes(mots):\n    \n\ndef plus_long_palindrome(mots):\n    ',
    hints:['Écris d’abord un test de palindrome (inverse lettre à lettre), utilise-le dans les deux fonctions.','plus_long_palindrome : champion = "" puis if len(mot) > len(champion) — seulement pour les palindromes.'],
    solution:'def est_pal(mot):\n    inverse = ""\n    for lettre in mot:\n        inverse = lettre + inverse\n    return mot == inverse\n\ndef garder_palindromes(mots):\n    return [m for m in mots if est_pal(m)]\n\ndef plus_long_palindrome(mots):\n    champion = ""\n    for m in mots:\n        if est_pal(m) and len(m) > len(champion):\n            champion = m\n    return champion',
    tests:[{call:{fn:'garder_palindromes',args:[['radar','chat','kayak']],want:['radar','kayak']}},{call:{fn:'plus_long_palindrome',args:[['pop','radar','xx']],want:'radar'}},{hidden:true,call:{fn:'garder_palindromes',args:[[]],want:[]}},{hidden:true,call:{fn:'plus_long_palindrome',args:[['chat','chien']],want:''}},{hidden:true,call:{fn:'plus_long_palindrome',args:[['aa','bb']],want:'aa'}}]}},
 {jour:'Semaine 6',emoji:'🐺',name:'Le Loup des Voyelles',mini:'analyse de texte',
  desc:'Il dissèque chaque phrase : voyelles, longueurs, statistiques. Rien ne lui échappe.',
  challenges:[
   {title:'La meute des voyelles',
    lesson:'<p>Pour tester si une lettre est une voyelle, <code>in</code> sur une chaîne suffit :</p><pre>if lettre in "aeiou":</pre>',
    task:'<b>Mission :</b> écris <code>compter_voyelles(mot)</code> qui renvoie le nombre de voyelles (a, e, i, o, u) du mot.',
    starter:'def compter_voyelles(mot):\n    ',
    hints:['total = 0 puis boucle sur chaque lettre.','if lettre in "aeiou": total = total + 1'],
    solution:'def compter_voyelles(mot):\n    total = 0\n    for lettre in mot:\n        if lettre in "aeiou":\n            total = total + 1\n    return total',
    tests:[{call:{fn:'compter_voyelles',args:['loup'],want:2}},{call:{fn:'compter_voyelles',args:['nuit'],want:2}},{call:{fn:'compter_voyelles',args:['brr'],want:0}}]},
   {title:'Le plus long hurlement',
    lesson:'<p>Trouver le mot le plus long d’une liste : le pattern du champion, appliqué à <code>len()</code>. (max interdit, évidemment.)</p>',
    task:'<b>Mission :</b> écris <code>plus_long(mots)</code> qui renvoie le mot le plus long (le premier en cas d’égalité ; la liste n’est jamais vide).',
    starter:'def plus_long(mots):\n    ',forbid:['max'],
    hints:['champion = mots[0] puis compare les len().','if len(m) > len(champion): champion = m — strictement supérieur pour garder le premier.'],
    solution:'def plus_long(mots):\n    champion = mots[0]\n    for m in mots:\n        if len(m) > len(champion):\n            champion = m\n    return champion',
    tests:[{call:{fn:'plus_long',args:[['le','loup','hurle']],want:'hurle'}},{call:{fn:'plus_long',args:[['aa','bb']],want:'aa'}}]},
   {title:'La phrase muette',
    lesson:'<p>Construire une nouvelle chaîne en FILTRANT : on n’ajoute que les lettres qu’on veut garder.</p><pre>resultat = resultat + lettre</pre>',
    task:'<b>Mission :</b> écris <code>sans_voyelles(mot)</code> qui renvoie le mot privé de ses voyelles (a, e, i, o, u).',
    starter:'def sans_voyelles(mot):\n    ',
    hints:['resultat = "" puis boucle sur les lettres.','if lettre not in "aeiou": resultat = resultat + lettre'],
    solution:'def sans_voyelles(mot):\n    resultat = ""\n    for lettre in mot:\n        if lettre not in "aeiou":\n            resultat = resultat + lettre\n    return resultat',
    tests:[{call:{fn:'sans_voyelles',args:['python'],want:'pythn'}},{call:{fn:'sans_voyelles',args:['aeiou'],want:''}},{call:{fn:'sans_voyelles',args:['grr'],want:'grr'}}]}],
  projet:{title:'PROJET · Le rapport du Loup',
    lesson:'<p>🏗️ <b>Grand Projet !</b> Le Loup veut un rapport complet sur chaque phrase : nombre de mots, total de voyelles, mot le plus long — le tout rangé dans UN dictionnaire. C’est exactement ce que fait un vrai analyseur de texte.</p>',
    task:'<b>Mission :</b> écris <code>analyse(phrase)</code> qui renvoie le dictionnaire <code>{"mots": nombre de mots, "voyelles": total de voyelles, "plus_long": le mot le plus long}</code> (premier en cas d’égalité ; la phrase contient toujours au moins un mot).',
    starter:'def analyse(phrase):\n    mots = phrase.split()\n    ',
    hints:['Trois calculs sur la liste mots : len(mots), une double boucle pour les voyelles, le champion pour le plus long.','return {"mots": ..., "voyelles": ..., "plus_long": ...}'],
    solution:'def analyse(phrase):\n    mots = phrase.split()\n    voyelles = 0\n    for m in mots:\n        for lettre in m:\n            if lettre in "aeiou":\n                voyelles = voyelles + 1\n    champion = mots[0]\n    for m in mots:\n        if len(m) > len(champion):\n            champion = m\n    return {"mots": len(mots), "voyelles": voyelles, "plus_long": champion}',
    tests:[{call:{fn:'analyse',args:['le loup hurle fort'],want:{__dict__:{mots:4,voyelles:6,plus_long:'hurle'}}}},{call:{fn:'analyse',args:['python'],want:{__dict__:{mots:1,voyelles:1,plus_long:'python'}}}},{hidden:true,call:{fn:'analyse',args:['brr grr'],want:{__dict__:{mots:2,voyelles:0,plus_long:'brr'}}}}]}}
]});
